import { getDB } from './database';

/**
 * Preguntas oficiales publicadas por la DGT en la revista
 * "Tráfico y Seguridad Vial" (tests de marzo 2024 a junio 2026).
 * Preguntas reales con su respuesta correcta oficial.
 */
export function seedPreguntasOficiales(): void {
  const db = getDB();

  const marca = db.prepare("SELECT 1 FROM seed_meta WHERE marca = 'preguntas_oficiales_v3'").get();
  if (marca) return;

  const temaMap: Record<string, number> = {};
  const temas = db.prepare('SELECT id, slug FROM temas').all() as { id: number; slug: string }[];
  for (const t of temas) {
    temaMap[t.slug] = t.id;
  }

  const selectExistente = db.prepare('SELECT 1 FROM preguntas WHERE texto = ?');

  const insertPregunta = db.prepare(
    'INSERT INTO preguntas (texto, opciones, indice_correcta, tema_id, dificultad, referencia_manual, explicacion, imagen) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
  );

  interface PreguntaOficial {
    texto: string;
    opciones: string[];
    indice_correcta: number;
    tema_slug: string;
    dificultad: number;
    referencia_manual: string;
    explicacion: string;
  }

  const preguntas: PreguntaOficial[] = [
    // =====================
    // TEST DICIEMBRE 2025
    // =====================
    {
      texto: 'A un turismo, ¿le está permitido circular si tiene roto el espejo retrovisor exterior izquierdo?',
      opciones: ['Sí, porque el retrovisor exterior izquierdo no es obligatorio', 'Solo si el vehículo tiene espejo retrovisor interior', 'No, cuando el conductor no pueda ver la circulación por detrás del vehículo'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#retrovisores',
      explicacion: 'El turismo debe permitir al conductor ver la circulación por detrás. Si el retrovisor está roto y no se ve, no se debe circular.',
    },
    {
      texto: '¿Qué es un microsueño?',
      opciones: ['Un periodo de unos segundos durante el cual el conductor sueña mientras conduce', 'Un periodo de unos segundos durante el cual el conductor queda ligeramente dormido sin darse cuenta', 'Un periodo corto de descanso que el conductor realiza cuando siente fatiga'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'El microsueño es un episodio de unos segundos en el que el conductor se queda dormido sin apenas darse cuenta.',
    },
    {
      texto: 'En una retención en la que están los vehículos detenidos, ¿está permitido usar el teléfono móvil?',
      opciones: ['No, excepto en vías urbanas', 'Únicamente con un dispositivo de manos libres y sin usar auriculares', 'Sí, porque el vehículo no está en movimiento'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#movil',
      explicacion: 'Aunque el vehículo esté detenido en una retención, solo puede usarse el teléfono con un sistema de manos libres y sin auriculares.',
    },
    {
      texto: 'Una luz verde en forma de flecha apuntando hacia abajo en un semáforo de carril...',
      opciones: ['obliga a no abandonar el carril sobre el que está colocada', 'exime de la obligación de detenerse ante una luz roja circular', 'no exime de tener que cumplir las normas generales sobre prioridad de paso'],
      indice_correcta: 2,
      tema_slug: 'prioridad',
      dificultad: 2,
      referencia_manual: 'prioridad#semaforos',
      explicacion: 'La flecha verde hacia abajo autoriza a circular por el carril, pero no exime de cumplir las normas de prioridad.',
    },
    {
      texto: 'Entre la puesta y la salida del sol, ¿puede encender la luz de largo alcance en caso de niebla?',
      opciones: ['Sí, procurando no deslumbrar a otros usuarios de la vía', 'Solo en carreteras con un carril para cada sentido', 'No, está prohibido'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 2,
      referencia_manual: 'luces#niebla',
      explicacion: 'En caso de niebla puede usarse la luz de largo alcance fuera de poblado, sin deslumbrar a otros usuarios.',
    },
    {
      texto: 'En un paso para peatones, si no funciona el semáforo, ¿es obligatorio ceder el paso a los peatones que intenten cruzar?',
      opciones: ['Sí, porque los peatones tienen prioridad de paso', 'No, porque los vehículos tienen prioridad de paso', 'Solo si quien intenta cruzar es una fila de escolares'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#peatones',
      explicacion: 'Los peatones tienen prioridad en los pasos de peatones, incluso si el semáforo no funciona.',
    },
    {
      texto: 'Un turismo con el distintivo ambiental clasificado como ECO, ¿está autorizado a circular por el carril VAO si su único ocupante es el conductor?',
      opciones: ['Sí, siempre que lleve el distintivo adhesivo en el parabrisas', 'No, salvo que por los paneles de mensaje variable se autorice su acceso', 'Sí, aunque no lleve el distintivo adhesivo'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#vado',
      explicacion: 'El carril VAO exige un número mínimo de ocupantes. Con un único ocupante no puede usarse, salvo autorización expresa.',
    },
    {
      texto: 'En las proximidades de vías de uso exclusivo de ciclos, ¿qué precauciones se deben tomar?',
      opciones: ['Hacer señales acústicas para indicar nuestra presencia', 'Moderar la velocidad y, si fuera preciso, detener el vehículo', 'Mantener la velocidad y estar atento a la señalización vertical'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#ciclistas',
      explicacion: 'Cerca de vías para ciclos hay que moderar la velocidad y detenerse si es preciso, pues los ciclistas son vulnerables.',
    },
    {
      texto: '¿Está permitido circular con un turismo por una vía en cuyo acceso está situada la señal de vía reservada para ciclos?',
      opciones: ['No, porque es una vía reservada para todos los vehículos de dos ruedas', 'No, porque es una vía reservada para ciclos', 'Sí, porque es una vía permitida para todos los vehículos, excepto ciclos'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#vias-reservadas',
      explicacion: 'La señal R-407 indica vía reservada para ciclos; está prohibida la entrada a cualquier otro vehículo.',
    },
    {
      texto: '¿Está permitido estacionar en doble fila?',
      opciones: ['Sí, siempre que el conductor no abandone el vehículo', 'No, en ningún caso', 'Solo cuando la duración del estacionamiento sea inferior a dos minutos'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#estacionamiento',
      explicacion: 'El estacionamiento en doble fila está totalmente prohibido; solo se permite la parada breve mientras el conductor permanezca.',
    },
    {
      texto: 'En una vía fuera de poblado en la que no exista zona peatonal ni arcén practicable, ¿está permitido que un peatón circule por la calzada?',
      opciones: ['Sí, siempre que tome las debidas precauciones', 'Solo si arrastra un vehículo de reducidas dimensiones', 'No'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#peatones',
      explicacion: 'Si no hay arcén practicable ni zona peatonal, los peatones pueden circular por la calzada tomando precauciones.',
    },
    {
      texto: '¿Cuál es uno de los problemas que, por el deterioro de sus aptitudes psicofísicas, encuentran muchas personas mayores como peatones en las vías públicas?',
      opciones: ['Tienen mayor capacidad de orientación', 'No aprecian bien la velocidad a la que se acercan los vehículos', 'Los bordillos de las aceras están al mismo nivel que la calzada'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#peatones',
      explicacion: 'Las personas mayores suelen tener más dificultades para apreciar la velocidad y distancia de los vehículos que se aproximan.',
    },
    {
      texto: 'Acaba de comprar un turismo nuevo; ¿cuándo debe presentarlo a la primera inspección técnica reglamentaria?',
      opciones: ['A los cuatro años, a contar desde la fecha de compra', 'A los dos años, a contar desde la fecha de matriculación', 'A los cuatro años, a contar desde la fecha de matriculación'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#itv',
      explicacion: 'Los turismos nuevos deben pasar su primera ITV a los cuatro años desde la fecha de matriculación.',
    },
    {
      texto: 'Si quiere abandonar una autovía, ¿en qué momento debe entrar en el carril de deceleración?',
      opciones: ['Lo antes posible', 'Es indiferente, en cualquier momento mientras la línea sea discontinua', 'Lo más tarde posible'],
      indice_correcta: 0,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#autovia',
      explicacion: 'Hay que entrar en el carril de deceleración lo antes posible para reducir la velocidad sin estorbar.',
    },
    {
      texto: '¿Qué debe hacer si un vehículo de la policía de tráfico se sitúa detrás de usted y enciende un dispositivo con una luz roja destelleante hacia delante?',
      opciones: ['Detenerse donde sea más seguro', 'Continuar la marcha hasta el próximo control', 'Detenerse inmediatamente donde se encuentre'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#policia',
      explicacion: 'Ante la señal de la policía, debe detenerse en el lugar más seguro posible, sin frenadas bruscas.',
    },
    // =====================
    // TEST JUNIO 2025
    // =====================
    {
      texto: 'De día es obligatorio encender el alumbrado correspondiente cuando se circule...',
      opciones: ['por un puente móvil', 'por un carril reservado a vehículos de alta ocupación (VAO)', 'por pasos inferiores o tramos de vía afectados por la señal Túnel'],
      indice_correcta: 2,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#tuneles',
      explicacion: 'De día hay que encender el alumbrado al circular por túneles o tramos señalizados como túnel.',
    },
    {
      texto: 'Entre los siguientes tipos de señales, ¿cuál es el orden de prioridad?',
      opciones: ['Señales verticales, agentes y semáforos', 'Agentes, semáforos y señales verticales', 'Semáforos, agentes y señales verticales'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#prioridad',
      explicacion: 'Tienen prioridad los agentes; después los semáforos; y por último las señales verticales y horizontales.',
    },
    {
      texto: 'En general, bajo los efectos de la cocaína el conductor...',
      opciones: ['es inseguro e infravalora sus capacidades al volante', 'se concentra mejor, por lo que sus decisiones son más seguras', 'es competitivo e impulsivo'],
      indice_correcta: 2,
      tema_slug: 'alcohol',
      dificultad: 2,
      referencia_manual: 'alcohol#drogas',
      explicacion: 'La cocaína vuelve al conductor más competitivo e impulsivo, con una falsa sensación de seguridad.',
    },
    {
      texto: 'Las embarazadas, ¿están obligadas a utilizar el cinturón de seguridad?',
      opciones: ['Sí, como norma general', 'No, porque es peligroso para el feto', 'Solo si no les dificulta los movimientos para conducir'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#cinturon',
      explicacion: 'Las embarazadas deben usar el cinturón de seguridad, colocando la banda abdominal bajo el abdomen.',
    },
    {
      texto: 'El calor afecta negativamente a las capacidades para conducir. Un conductor bajo sus efectos normalmente...',
      opciones: ['tarda más en reaccionar y es menos agresivo', 'tarda más en reaccionar y es más agresivo', 'tarda menos en reaccionar y es más agresivo'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#calor',
      explicacion: 'El calor aumenta el tiempo de reacción y favorece un comportamiento más agresivo e irritabilidad.',
    },
    {
      texto: 'Cuando la luz de marcha atrás esté averiada, ¿cómo debe indicar que va a dar marcha atrás?',
      opciones: ['Moviendo el brazo de arriba abajo', 'Con el brazo extendido y la palma de la mano hacia atrás', 'Advirtiéndolo con el claxon'],
      indice_correcta: 1,
      tema_slug: 'luces',
      dificultad: 2,
      referencia_manual: 'luces#marcha-atras',
      explicacion: 'Si la luz de marcha atrás no funciona, la maniobra se indica con el brazo extendido y la palma hacia atrás.',
    },
    {
      texto: 'En una vía interurbana con un carril por sentido, ¿dónde se colocará un ciclomotor para girar a la izquierda, si no existe carril específico?',
      opciones: ['En el eje de la calzada, sin invadir el carril de sentido contrario', 'En la parte central del carril por el que circule', 'A la derecha, fuera de la calzada siempre que sea posible'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#giros',
      explicacion: 'Los ciclomotores deben girar a la izquierda colocándose a la derecha, fuera de la calzada si es posible.',
    },
    {
      texto: 'Para intentar evitar la aparición de la somnolencia durante la conducción es aconsejable dormir...',
      opciones: ['entre 5 y 7 horas diarias', 'menos horas de las necesarias para mantener el nivel de alerta', 'las horas suficientes para estar descansado, entre 7 y 9 horas'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'Dormir entre 7 y 9 horas diarias es lo recomendable para mantener la atención durante la conducción.',
    },
    {
      texto: '¿Cómo debe comportarse el conductor de un turismo, sobre todo en vías urbanas, para evitar un accidente con una motocicleta o un ciclomotor?',
      opciones: ['Circular en paralelo y lo más cerca posible de los vehículos de dos ruedas', 'Mirar por los retrovisores con frecuencia', 'Reducir o incluso eliminar la distancia de seguridad'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#motos',
      explicacion: 'Mirar con frecuencia los retrovisores y comprobar los ángulos muertos es esencial para evitar accidentes con motos.',
    },
    {
      texto: 'En un carril habilitado en sentido contrario al habitual por trabajos en la calzada, ¿qué vehículos tienen permitido utilizarlo?',
      opciones: ['Todos los que estén autorizados a circular por la vía', 'Solo turismos y motocicletas', 'Automóviles que no superen los 3.500 kg de M.M.A. y motocicletas'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#obras',
      explicacion: 'El carril habilitado en sentido contrario puede ser utilizado por todos los vehículos autorizados a circular por esa vía.',
    },
    {
      texto: 'En los adelantamientos a ciclistas en vías con un carril para cada sentido, ¿está permitido ocupar el carril de sentido contrario?',
      opciones: ['Sí, siempre que el adelantamiento se pueda realizar con seguridad', 'No', 'Solo si ambos sentidos están separados por línea blanca discontinua'],
      indice_correcta: 0,
      tema_slug: 'adelantamientos',
      dificultad: 1,
      referencia_manual: 'adelantamientos#ciclistas',
      explicacion: 'Para adelantar a un ciclista con seguridad puede invadirse el carril contrario, dejando al menos 1,5 metros de separación.',
    },
    {
      texto: 'Los conductores, ¿están obligados a realizar las pruebas de alcoholemia cuando sean requeridos por la policía de tráfico?',
      opciones: ['No; pueden negarse y seguir circulando', 'Solo están obligados en caso de accidente de tráfico', 'Sí; negarse a realizarla es un delito incluido en el Código Penal'],
      indice_correcta: 2,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#tasas',
      explicacion: 'Negarse a realizar la prueba de alcoholemia es un delito recogido en el Código Penal.',
    },
    {
      texto: '¿Es conveniente utilizar un aceite lubricante con un índice de viscosidad tan bajo que, al calentarse el motor, se vuelva excesivamente líquido?',
      opciones: ['No, porque el aceite no llega a engrasar bien las piezas del motor', 'Sí; cuanto más líquido, mejor engrasa y arrastra los residuos', 'Solo si el motor se calienta en exceso'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#mantenimiento',
      explicacion: 'Un aceite demasiado líquido en caliente no lubrica correctamente y puede dañar el motor.',
    },
    // =====================
    // TEST ABRIL 2025
    // =====================
    {
      texto: '¿Está permitido circular con un vehículo cuyas placas de matrícula presentan obstáculos que impiden o dificultan su lectura e identificación?',
      opciones: ['No; el conductor debe verificar que las placas se pueden leer correctamente', 'Sí, siempre que la placa delantera se pueda leer correctamente', 'Sí, siempre que el vehículo solo circule por vías urbanas'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#matricula',
      explicacion: 'Las placas de matrícula deben estar siempre en perfecto estado y ser legibles para identificar el vehículo.',
    },
    {
      texto: 'Respecto al uso del cinturón de seguridad, como norma general, el ocupante de un turismo distinto del conductor está obligado a...',
      opciones: ['llevarlo puesto y sin abrochar', 'llevarlo puesto y abrochado solo en vías interurbanas', 'llevarlo puesto y correctamente abrochado'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#cinturon',
      explicacion: 'Todos los ocupantes deben llevar el cinturón abrochado y correctamente ajustado, en cualquier tipo de vía.',
    },
    {
      texto: 'En vías interurbanas con tres carriles para el mismo sentido, ¿le está permitido circular por el carril izquierdo a un turismo con remolque?',
      opciones: ['Sí, cuando la longitud del conjunto no supere los 7 metros', 'Sí, pero solo para adelantar a otros vehículos', 'No, en ningún caso'],
      indice_correcta: 0,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#carriles',
      explicacion: 'Los conjuntos de vehículos de más de 7 metros no pueden usar el carril izquierdo; si no supera los 7 metros, sí.',
    },
    {
      texto: 'Cuando se adelante a vehículos de tracción animal, fuera de poblado, la separación lateral...',
      opciones: ['no debe ser inferior a 1,5 metros', 'debe ser inferior a 1,5 metros, en todos los casos', 'debe ser siempre proporcional a la anchura y características de la vía'],
      indice_correcta: 0,
      tema_slug: 'adelantamientos',
      dificultad: 1,
      referencia_manual: 'adelantamientos#traccion-animal',
      explicacion: 'Al adelantar vehículos de tracción animal fuera de poblado, la separación lateral mínima es de 1,5 metros.',
    },
    {
      texto: '¿Qué alumbrado deberá dejar encendido, como norma general, el conductor de un vehículo inmovilizado entre la puesta y la salida del sol en el arcén de una travesía insuficientemente iluminada?',
      opciones: ['Ninguno', 'Las luces de emergencia', 'Las luces de posición'],
      indice_correcta: 2,
      tema_slug: 'luces',
      dificultad: 2,
      referencia_manual: 'luces#parada',
      explicacion: 'Un vehículo inmovilizado en el arcén de una travesía insuficientemente iluminada debe dejar las luces de posición encendidas.',
    },
    {
      texto: 'Esta señal de peligro con un coche deslizándose advierte de...',
      opciones: ['la proximidad de un escalón lateral o desnivel', 'la proximidad de pavimento deslizante por hielo o nieve', 'la proximidad de una zona de la calzada cuyo pavimento puede resultar muy deslizante'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#peligro',
      explicacion: 'La señal P-1e advierte de pavimento deslizante: una zona donde el firme puede estar muy resbaladizo.',
    },
    {
      texto: '¿Qué alteración provoca con mayor frecuencia el consumo de alcohol en el comportamiento del conductor?',
      opciones: ['Respuestas impulsivas y agresivas ante los demás conductores', 'Disminución del tiempo de reacción', 'Mayor facilidad para percibir los semáforos'],
      indice_correcta: 0,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#efectos',
      explicacion: 'El alcohol provoca respuestas impulsivas y agresivas, además de aumentar el tiempo de reacción.',
    },
    {
      texto: '¿Qué indica la señal V-4 colocada en la parte posterior de un vehículo?',
      opciones: ['Que transporta mercancías peligrosas', 'Que es un vehículo especial realizando trabajos en la vía', 'Que es un vehículo lento y no puede superar los 40 km/h'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#vehiculos',
      explicacion: 'La señal V-4 identifica vehículos lentos que no pueden superar los 40 km/h, como tractores o ciclomotores de obras.',
    },
    {
      texto: 'Si ha dormido mal o no ha dormido lo suficiente debe tener en cuenta que...',
      opciones: ['conducir por una autovía durante horas impide la aparición del sueño', 'no se encuentra en perfectas condiciones para conducir', 'una taza de café elimina la fatiga y le ayuda a concentrarse'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'La falta de sueño reduce las capacidades del conductor; la mejor medida es descansar antes de conducir.',
    },
    {
      texto: '¿Con qué dos factores suelen relacionarse muchos de los accidentes más graves que sufren los jóvenes conductores?',
      opciones: ['El consumo de alcohol y drogas y una actitud prudente', 'La falta de experiencia al volante y el consumo de alcohol y drogas', 'La velocidad excesiva y una adecuada percepción del riesgo'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#jovenes',
      explicacion: 'La inexperiencia junto con el consumo de alcohol y drogas son factores clave en los accidentes graves de jóvenes.',
    },
    {
      texto: '¿Cuál de las siguientes circunstancias hace que aumente el consumo de combustible?',
      opciones: ['Circular con las ventanillas del vehículo subidas', 'Circular con el vehículo muy cargado', 'Circular con unos neumáticos que carezcan de dibujo'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#conduccion-eficiente',
      explicacion: 'El exceso de carga aumenta el consumo de combustible. Los neumáticos sin dibujo y las ventanillas abiertas también lo aumentan.',
    },
    {
      texto: '¿Cuál de las siguientes razones puede explicar que el vehículo sea el factor de riesgo que aparece en menor grado como causa principal de los accidentes de tráfico?',
      opciones: ['Las importantes mejoras técnicas introducidas en su diseño y construcción', 'Que la edad media de los vehículos es cada vez mayor', 'Que en los últimos 20 años los kilómetros recorridos han disminuido'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#factor-vehiculo',
      explicacion: 'Las mejoras técnicas de los vehículos (ABS, ESP, airbags) reducen su peso como causa de accidentes.',
    },
    {
      texto: 'Para mantener la seguridad, ¿qué elementos se deben revisar periódicamente y con mayor frecuencia que el resto de componentes del vehículo?',
      opciones: ['Los neumáticos, el sistema de frenado y los amortiguadores', 'Las luces, la batería y las llantas', 'El filtro del aire, la dirección y los retrovisores'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#mantenimiento',
      explicacion: 'Neumáticos, frenos y amortiguadores son los elementos que más influyen en la seguridad y requieren revisión frecuente.',
    },
    {
      texto: 'Una luz roja intermitente o dos luces rojas alternativamente intermitentes de un semáforo...',
      opciones: ['permiten el paso con precaución', 'prohíben temporalmente el paso', 'obligan a moderar la velocidad antes de pasar'],
      indice_correcta: 1,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#semaforos',
      explicacion: 'La luz roja intermitente prohíbe el paso temporalmente, como en pasos a nivel o a la espera de nueva señalización.',
    },
    {
      texto: 'En general, un conductor que sufre un trastorno depresivo...',
      opciones: ['recoge mejor la información relevante', 'es más fácil que se distraiga y que sufra somnolencia', 'se concentra con mayor facilidad'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#aptitud',
      explicacion: 'Los trastornos como la depresión favorecen la distracción y la somnolencia, reduciendo la seguridad al volante.',
    },
    {
      texto: 'En una vía de doble sentido, ¿qué vehículos deben guardar una separación mínima de 50 metros con el vehículo de delante cuando no pretendan adelantar?',
      opciones: ['Todos los camiones, con independencia de su M.M.A.', 'Los conjuntos de vehículos de más de 10 metros de longitud', 'Los turismos'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#distancia-seguridad',
      explicacion: 'Los conjuntos de vehículos de más de 10 metros deben mantener 50 metros de separación con el vehículo que les precede.',
    },
    {
      texto: '¿Existe riesgo de accidente si un conductor utiliza un dispositivo de manos libres para hablar por teléfono mientras conduce?',
      opciones: ['No; el dispositivo está pensado para que no exista ningún riesgo', 'Solo si la conversación dura más de cinco minutos', 'Sí, hay cierto riesgo porque disminuye la atención'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#movil',
      explicacion: 'Aunque sea manos libres, la conversación disminuye la atención y supone un riesgo de distracción.',
    },
    {
      texto: '¿Qué factor de riesgo ocasiona un mayor número de accidentes de tráfico?',
      opciones: ['El factor humano', 'El factor vía y su entorno', 'El factor vehículo'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#factor-humano',
      explicacion: 'El factor humano es el que interviene en la mayor parte de los accidentes de tráfico.',
    },
    {
      texto: 'Como norma general, ¿cómo se denomina el tramo de carretera que discurre por poblado?',
      opciones: ['Carretera convencional', 'Travesía', 'Autovía'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#travesia',
      explicacion: 'El tramo de carretera que discurre por poblado se denomina travesía.',
    },
    {
      texto: 'Si una intersección con prioridad de paso está saturada y es previsible que se quede detenido sin terminar de atravesarla, impidiendo la circulación transversal, ¿qué debe hacer?',
      opciones: ['Entrar en la intersección, porque tiene prioridad de paso', 'Tocar el claxon con insistencia', 'No entrar en la intersección'],
      indice_correcta: 2,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#intersecciones',
      explicacion: 'No debe entrar en la intersección si previsiblemente va a quedar detenido en medio, bloqueando la circulación.',
    },
    {
      texto: 'La distancia de frenado está determinada por...',
      opciones: ['un único factor, la velocidad a la que se circula', 'varios factores, como la velocidad, el estado de la vía o el del vehículo', 'un único factor, el estado del vehículo'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#distancia-seguridad',
      explicacion: 'La distancia de frenado depende de la velocidad, el estado del firme, los frenos, los neumáticos y la carga.',
    },
    {
      texto: '¿Qué puede verse afectado si cambia el carenado de una motocicleta?',
      opciones: ['La estética, exclusivamente', 'La aerodinámica y el consumo', 'La visibilidad del vehículo'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#motos',
      explicacion: 'Modificar el carenado altera la aerodinámica y el consumo de la motocicleta.',
    },
    // =====================
    // TEST OCTUBRE 2025
    // =====================
    {
      texto: 'Si existen semáforos con indicaciones distintas a la derecha y a la izquierda, ¿a cuál obedecerán los que pretendan seguir de frente?',
      opciones: ['Al situado a su derecha', 'Al que se encuentre más cerca del vehículo', 'Al situado inmediatamente a su izquierda'],
      indice_correcta: 2,
      tema_slug: 'prioridad',
      dificultad: 2,
      referencia_manual: 'prioridad#semaforos',
      explicacion: 'Si hay semáforos a ambos lados con indicaciones distintas, se obedece al que está más cerca, es decir, el de la izquierda para seguir de frente.',
    },
    {
      texto: 'En el centro de la calzada hay doble línea continua; ¿qué indica?',
      opciones: ['Que la calzada es peligrosa', 'Que hay un carril especial', 'Que no se puede atravesar, ni pisar la línea'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#marcas-viales',
      explicacion: 'La doble línea continua prohíbe atravesarla o circular sobre ella en ningún sentido.',
    },
    {
      texto: 'Al cruzar un arcén por el que transitan peatones, ¿qué debe hacer?',
      opciones: ['Avisarles mediante señales acústicas para que se aparten', 'Cederles el paso, pero solamente si forman un grupo', 'Cederles el paso si no disponen de zona peatonal'],
      indice_correcta: 2,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#peatones',
      explicacion: 'El vehículo debe ceder el paso a los peatones que transitan por el arcén si no disponen de otro lugar por el que circular.',
    },
    {
      texto: 'Esta señal de reglamentación con una flecha roja a la izquierda, ¿prohíbe cambiar de sentido?',
      opciones: ['No', 'Sí, pero no prohíbe girar a la derecha', 'Sí; prohíbe realizar cualquier giro'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#prohibicion',
      explicacion: 'La señal R-103 prohíbe realizar un cambio de sentido, pero no impide girar a la derecha derivarsi las prohibiciones concretas.',
    },
    {
      texto: 'Un furgón, ¿puede utilizar un carril reversible?',
      opciones: ['Solo si su M.M.A. no es superior a 3.500 kilogramos', 'No', 'Sí'],
      indice_correcta: 2,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#carriles',
      explicacion: 'Los furgones pueden utilizar el carril reversible como cualquier turismo, salvo que exista señalización que lo prohíba.',
    },
    {
      texto: 'Como norma general, en la parte transitable del arcén de una vía interurbana, ¿está permitida la parada o el estacionamiento?',
      opciones: ['Está permitida la parada, pero no el estacionamiento', 'Está prohibida tanto la parada como el estacionamiento', 'Está permitida tanto la parada como el estacionamiento'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#estacionamiento',
      explicacion: 'En el arcén de una vía interurbana está prohibido tanto parar como estacionar, salvo casos de emergencia o fuerza mayor.',
    },
    {
      texto: 'Circulando por una autopista observa que se ha pasado una salida, ¿puede volver a ella circulando marcha atrás?',
      opciones: ['No', 'Sí, si el recorrido no supera los 15 metros', 'Sí, si se comprueba que no existe peligro para otros usuarios'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#marcha-atras',
      explicacion: 'Está totalmente prohibido dar marcha atrás en autopistas y autovías. Hay que seguir hasta la siguiente salida.',
    },
    {
      texto: '¿Puede circular con su turismo si el equipaje no permite una visión adecuada de la vía por el espejo retrovisor interior?',
      opciones: ['No; en ningún caso la carga puede disminuir la visibilidad a través del retrovisor', 'Sí, si el vehículo lleva dos espejos retrovisores exteriores', 'Solo si el retrovisor derecho es gran angular'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#carga',
      explicacion: 'Si la carga impide la visión por el interior, puede circular siempre que los dos retrovisores exteriores permitan ver la vía.',
    },
    {
      texto: 'Se encuentra ante un paso a nivel con barreras que empiezan a descender, ¿qué debe hacer?',
      opciones: ['Acelerar para cruzarlo antes de que bajen', 'Detenerse y esperar a que las barreras suban y las luces se apaguen', 'Cruzar con precaución si no se ve el tren'],
      indice_correcta: 1,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#paso-nivel',
      explicacion: 'Al bajar las barreras hay que detenerse y esperar a que se abran y las luces rojas se apaguen antes de cruzar.',
    },
    {
      texto: 'En general, un conductor con sueño...',
      opciones: ['acepta un mayor nivel de riesgo en la conducción', 'acepta un menor nivel de riesgo', 'tarda menos en reaccionar ante un suceso'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'Con sueño se asume más riesgo y se tarda más en reaccionar: aumentan la distracción y el riesgo de accidente.',
    },
    {
      texto: '¿Cómo se conoce a los colectivos con mayor probabilidad de verse implicados en un accidente de tráfico o de fallecer a consecuencia del mismo?',
      opciones: ['Grupos de riesgo o vulnerables en el tráfico', 'Víctimas de accidentes de tráfico', 'Grupos en riesgo de exclusión social'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#vulnerables',
      explicacion: 'Se denominan grupos de riesgo o usuarios vulnerables a peatones, ciclistas y motoristas.',
    },
    {
      texto: '¿Puede sobresalir por la parte trasera del vehículo la carga indivisible de un turismo?',
      opciones: ['Sí, un máximo de hasta el 10% de la longitud del vehículo', 'No, la carga no puede sobresalir', 'Sí, un máximo de hasta el 15% de la longitud del vehículo'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#carga',
      explicacion: 'En turismos, la carga indivisible puede sobresalir por la parte trasera hasta el 15% de la longitud y debe señalizarse.',
    },
    {
      texto: 'Si queda detenido en un atasco, ¿qué distancia es aconsejable mantener con el vehículo de delante?',
      opciones: ['Un metro como máximo', 'La menor posible para ocupar menos', 'Dos o tres metros para no golpear al vehículo'],
      indice_correcta: 2,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#distancia-seguridad',
      explicacion: 'Ante un atasco conviene dejar 2-3 metros con el coche de delante para poder maniobrar con seguridad.',
    },
    {
      texto: '¿Qué condiciones deben tener los neumáticos de una motocicleta?',
      opciones: ['Las dos ruedas deben ser del mismo tamaño y características', 'La profundidad del dibujo debe ser de al menos 1,6 mm', 'No deben presentar ampollas, deformaciones anormales o roturas'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#neumaticos',
      explicacion: 'Los neumáticos no deben presentar ampollas, deformaciones ni roturas; además deben superar el mínimo legal de dibujo para motocicletas.',
    },
    // =====================
    // TEST DICIEMBRE 2024
    // =====================
    {
      texto: 'En una calzada de un solo sentido, ¿dónde debe situarse para cambiar de dirección a la izquierda?',
      opciones: ['Junto al borde izquierdo de la calzada', 'Junto al borde derecho de la calzada', 'En una calzada de un solo sentido no se puede cambiar de dirección'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#cambio-sentido',
      explicacion: 'En una calzada de un solo sentido, el giro a la izquierda se inicia desde el carril o borde más izquierdo.',
    },
    {
      texto: '¿Está permitido realizar una parada en una autovía o autopista?',
      opciones: ['Sí, en la mediana o en el arcén, indistintamente', 'Solo si el arcén es transitable y su anchura superior a 1,5 m', 'No, excepto en las zonas habilitadas'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#estacionamiento',
      explicacion: 'Solo se puede parar en autovías y autopistas en zonas habilitadas, como áreas de servicio o estacionamientos.',
    },
    {
      texto: '¿Debe entrar en una intersección en una situación en la que el tráfico esté tan saturado que, al detenerse, probablemente obstaculice la circulación transversal?',
      opciones: ['Solo si conduce un vehículo de servicio público', 'Sí, siempre que tenga prioridad de paso', 'No, aunque tenga prioridad de paso'],
      indice_correcta: 2,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#intersecciones',
      explicacion: 'No debe entrar en el cruce aunque tenga prioridad si va a quedar bloqueado en él, obstaculizando el tráfico.',
    },
    {
      texto: 'Cuando un conductor no supere la tasa máxima de alcohol permitida, el agente de tráfico, ¿puede realizarle una segunda prueba?',
      opciones: ['No, en ningún caso', 'Sí, si muestra signos evidentes de encontrarse bajo los efectos del alcohol', 'Solo si está implicado en un accidente'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 2,
      referencia_manual: 'alcohol#tasas',
      explicacion: 'Si el conductor muestra signos evidentes de embriaguez, el agente puede solicitar una segunda prueba.',
    },
    {
      texto: '¿Qué debe hacer si empieza a llover con intensidad mientras conduce una motocicleta?',
      opciones: ['Moderar la velocidad y detenerse si fuera preciso', 'Circular pegado a los vehículos pesados', 'Aumentar la velocidad'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#lluvia',
      explicacion: 'Ante lluvia intensa, la motocicleta debe moderar la velocidad e incluso, si es necesario, detenerse.',
    },
    {
      texto: '¿Qué advierte esta señal de peligro con un coche y líneas dispersas?',
      opciones: ['Obstrucción en la calzada', 'Proyección de gravilla', 'Visibilidad reducida'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#peligro',
      explicacion: 'La señal P-34 avisa de un tramo con visibilidad reducida, por ejemplo por curvas u obstáculos.',
    },
    {
      texto: 'Entre los efectos negativos de la velocidad se encuentra el efecto túnel, en el que el conductor...',
      opciones: ['solamente percibe el centro de la calzada y deja de ver los laterales', 'tiene la falsa sensación de que circula a velocidad reducida', 'percibe mejor los laterales que el centro'],
      indice_correcta: 0,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#efecto-tunel',
      explicacion: 'A mayor velocidad, el campo visual se estrecha y el conductor solo percibe el centro de la calzada: efecto túnel.',
    },
    {
      texto: '¿Cómo debe colocar el navegador GPS portátil en el vehículo?',
      opciones: ['Debajo del volante o cerca del suelo', 'Justo detrás del volante a la altura de los ojos', 'Donde no entorpezca ni la visión ni el despliegue del airbag'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#distracciones',
      explicacion: 'El GPS debe colocarse donde no obstaculice la visibilidad ni el despliegue del airbag.',
    },
    {
      texto: '¿Cuál es una de las principales causas de los accidentes de las personas mayores?',
      opciones: ['El deterioro de las capacidades psicomotoras', 'El aumento de la visión periférica', 'Una mejor percepción y análisis de riesgos'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#mayores',
      explicacion: 'El deterioro de las capacidades psicomotoras al envejecer aumenta el riesgo de accidente.',
    },
    {
      texto: 'Todo conductor implicado en un accidente de tráfico, ¿está obligado a detenerse?',
      opciones: ['Solo si es culpable del accidente', 'Sí, pero de forma que no cree un nuevo peligro', 'No'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#accidente',
      explicacion: 'El implicado debe detenerse lo antes posible, sin obstaculizar la vía ni crear nuevos peligros.',
    },
    {
      texto: 'Si circula con la presión de inflado de los neumáticos descompensada, ¿aumenta el riesgo de perder el control?',
      opciones: ['Sí, la frenada es irregular y se reduce la estabilidad', 'No, ya que duplica el área de contacto de las cubiertas', 'Es indiferente'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#neumaticos',
      explicacion: 'Una presión incorrecta altera el comportamiento del vehículo, aumenta la distancia de frenado y el riesgo de perder el control.',
    },
    {
      texto: '¿Qué indica esta señal de vía reservada con la silueta de un ciclomotor?',
      opciones: ['Vía reservada a ciclomotores', 'Vía reservada a ciclos', 'Acceso prohibido a los ciclomotores'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#vias-reservadas',
      explicacion: 'La señal R-407 indica la vía reservada para ciclomotores; el resto de vehículos tienen prohibida la entrada.',
    },
    {
      texto: '¿Cuál de los tres factores de riesgo es el que está menos implicado entre las causas de los accidentes?',
      opciones: ['El factor vía y su entorno', 'El factor humano', 'El factor vehículo'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#factor-humano',
      explicacion: 'El factor humano aparece en torno al 90% de los accidentes; el vehículo es el menos implicado.',
    },
// =====================
    // TEST MARZO 2024
    // =====================
    {
      texto: 'Una vez termine de adelantar el vehículo verde, ¿puede seguir circulando por el carril izquierdo?',
      opciones: ['No, debe circular por el carril derecho', 'Sí, porque en autopista se puede circular por cualquier carril', 'Sí, pero solo si termina de adelantar'],
      indice_correcta: 0,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#carriles',
      explicacion: 'Tras terminar un adelantamiento hay que volver al carril derecho; el carril izquierdo solo se utiliza para adelantar.',
    },
    {
      texto: 'En caso de accidente, ¿existe relación entre la velocidad de circulación y la gravedad de las lesiones de los ocupantes de un vehículo?',
      opciones: ['Sí; a mayor velocidad menor es la probabilidad de sufrir lesiones graves', 'Sí; a mayor velocidad mayor es la probabilidad de sufrir lesiones graves', 'No; la gravedad de las lesiones depende solo de los sistemas de seguridad pasiva'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#distancia-seguridad',
      explicacion: 'Cuanto mayor es la velocidad de circulación, mayor es la energía del impacto y, por tanto, la gravedad de las lesiones.',
    },
    {
      texto: 'Un conductor se encuentra situado en el carril derecho de esta calzada señalizada con una flecha de dirección obligatoria, ¿puede seguir de frente?',
      opciones: ['Sí; puede girar a la derecha o continuar de frente', 'Sí, porque no existe una señal vertical que prohíba seguir de frente', 'No, está obligado a girar a la derecha'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#marcas-viales',
      explicacion: 'La señal de dirección obligatoria (por ejemplo R-2) obliga a circular en la dirección indicada y no permite seguir de frente.',
    },
    {
      texto: 'En un turismo con cinco plazas autorizadas, ¿se puede transportar a seis personas?',
      opciones: ['Sí, siempre que no se supere la masa máxima autorizada', 'Sí', 'No'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#carga',
      explicacion: 'Está prohibido superar el número de plazas autorizadas de un vehículo, con independencia de la masa.',
    },
    {
      texto: 'El sueño y la fatiga, ¿cómo influyen en la conducción?',
      opciones: ['Disminuyen el tiempo de reacción', 'Aumentan la capacidad de reacción', 'Aumentan la distancia de reacción'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'El sueño y la fatiga aumentan el tiempo y la distancia de reacción, y reducen la capacidad de conducir.',
    },
    {
      texto: 'Si se ve implicado en un accidente de tráfico con posibilidad de muertos o heridos graves, ¿qué actuaciones, entre otras, debe llevar a cabo en la medida de lo posible?',
      opciones: ['Seguir circulando, sin prestar ayuda a las víctimas ni avisar a la autoridad', 'Detener el vehículo sin provocar nuevos peligros y prestar auxilio a las víctimas', 'Detenerse, hacerse cargo de las víctimas y realizar la maniobra'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#accidente',
      explicacion: 'Ante un accidente hay que detenerse sin provocar nuevos peligros y prestar auxilio a las víctimas.',
    },
    {
      texto: 'Cuando son víctimas de atropello, las lesiones más graves en los ciclistas, que pueden incluso provocar la muerte, se localizan en...',
      opciones: ['la cabeza', 'las piernas', 'las manos'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#vulnerables',
      explicacion: 'Las lesiones en la cabeza son las más graves en los atropellos a ciclistas y las que pueden resultar mortales.',
    },
    {
      texto: 'En esta carretera convencional con arcén transitable, ¿por dónde debe circular un ciclomotor?',
      opciones: ['Por el centro de la calzada o por el arcén de la derecha', 'Por la calzada, lo más cerca posible del borde derecho', 'Por el arcén de la derecha'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#ciclomotores',
      explicacion: 'Si existe arcén transitable, el ciclomotor debe circular por el arcén de la derecha, y no por la calzada.',
    },
    {
      texto: 'En un control preventivo, ¿pueden los agentes someter a un conductor a una prueba de detección de estupefacientes?',
      opciones: ['Sí', 'No; es una prueba que solo se puede realizar en un centro médico', 'Solo si está implicado en un accidente'],
      indice_correcta: 0,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#drogas',
      explicacion: 'En los controles preventivos, los agentes pueden solicitar pruebas de detección de alcohol y drogas.',
    },
    {
      texto: 'Circula por una calzada en la que, debido a la niebla, el pavimento está húmedo y resbaladizo. ¿Cómo debe ser la conducción?',
      opciones: ['Dinámica y a una velocidad elevada para evitar que las ruedas patinen', 'Suave, sin movimientos bruscos, reduciendo la velocidad y aumentando la distancia de seguridad', 'Igual que cuando la calzada está seca, ya que los neumáticos no pierden adherencia'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#aquaplaning',
      explicacion: 'Con pavimento mojado o resbaladizo hay que conducir de forma suave, moderar la velocidad y aumentar la distancia de seguridad.',
    },
    {
      texto: 'En una zona cebreada de la calzada, ¿pueden los conductores circular o pararse sobre ella?',
      opciones: ['Pararse sí pueden, pero circular está prohibido', 'Sí, todos los conductores pueden tanto pararse como circular sobre ella', 'No, no pueden ni circular ni pararse sobre ella'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#marcas-viales',
      explicacion: 'Las zonas cebreadas delimitan zonas donde no se puede circular ni detenerse.',
    },
    {
      texto: 'En poblado, ¿está permitido usar las advertencias acústicas?',
      opciones: ['Sí, para evitar un accidente o avisar de la realización de un servicio de urgencia', 'Sí, exclusivamente para evitar un accidente', 'No'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#advertencias-acusticas',
      explicacion: 'En poblado solo se puede tocar el claxon para evitar un accidente o para avisar de un servicio de urgencia.',
    },
    {
      texto: 'Conduce un turismo con un remolque de un solo eje. ¿Le afecta la señal de prohibición de circulación de vehículos con remolque de un solo eje?',
      opciones: ['Sí, porque lleva un remolque de un eje', 'No', 'Solo si la M.M.A. del remolque supera la cifra indicada en la señal'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#prohibicion',
      explicacion: 'La señal prohíbe circular a los vehículos con remolque de un solo eje, salvo que la M.M.A. no supere la indicada.',
    },
    // =====================
    // TEST JUNIO 2024
    // =====================
    {
      texto: 'El consumo de alcohol, aunque sea en pequeñas cantidades...',
      opciones: ['No deteriora la capacidad para conducir', 'Deteriora la capacidad para conducir', 'Deteriora la capacidad para conducir solo si se mezcla con alguna droga ilegal'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#efectos',
      explicacion: 'Cualquier cantidad de alcohol, por pequeña que sea, deteriora las capacidades para conducir.',
    },
    {
      texto: 'Un adulto, ¿puede transportar a un pasajero en una bicicleta que por construcción no pueda ser ocupada por mas de una persona?',
      opciones: ['No, está prohibido', 'Sí, a un menor de hasta 7 años en un asiento adecuado y homologado', 'Sí, a un menor de hasta 12 años'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#ciclomotores',
      explicacion: 'Se permite transportar a un menor de hasta 7 años en un asiento adicional debidamente homologado.',
    },
    {
      texto: 'Delante de un vado, esta señal de prohibición prohíbe...',
      opciones: ['La parada y el estacionamiento', 'Únicamente la parada', 'Solamente el estacionamiento'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#prohibicion',
      explicacion: 'La señal de vado prohíbe únicamente el estacionamiento, no la parada delante del vado.',
    },
    {
      texto: 'A falta de señalización, ¿cuál es la velocidad máxima permitida para una furgoneta que circule por una autovía que discurre dentro de poblado?',
      opciones: ['100 km/h', '80 km/h', '90 km/h'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#autovia',
      explicacion: 'En vías dentro de poblado, la velocidad máxima general es 50 km/h; fuera de poblado, en autovía/autoesta, 80 km/h para furgones.',
    },
    {
      texto: 'Las menores de edad de estatura igual o inferior a 135 centímetros deberán utilizar sistemas de retención infantil homologados debidamente adaptados a...',
      opciones: ['Su talla y edad', 'Su edad y peso', 'Su talla y peso'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#infantil',
      explicacion: 'Los sistemas de retención infantil deben estar adaptados a la talla y peso del menor.',
    },
    {
      texto: 'En un carril reservado para uso exclusivo del transporte público urbano, ¿se puede estacionar?',
      opciones: ['Sí, fuera del horario de servicio', 'Sí, se puede parar y estacionar', 'No'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#estacionamiento',
      explicacion: 'En los carriles reservados para transporte público está prohibido parar y estacionar.',
    },
    {
      texto: 'Para los conductores y pasajeros de motocicletas, ¿tiene importancia el vestuario a utilizar?',
      opciones: ['No, es indiferente si llevan casco', 'Sí, es fundamental porque el cuerpo está directamente expuesto a las inclemencias del tiempo', 'No, porque no aporta nada a la seguridad'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#motos',
      explicacion: 'El vestuario y la protección son esenciales para los motoristas, ya que el cuerpo está expuesto directamente.',
    },
    {
      texto: '¿Es posible ahorrar combustible evitando cambios de marcha innecesarios?',
      opciones: ['Sí', 'No, en ningún caso', 'Depende de si el vehículo es diésel o de gasolina'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#conduccion-eficiente',
      explicacion: 'Evitar cambios de marcha innecesarios ayuda a ahorrar combustible.',
    },
    {
      texto: '¿Qué debe hacer el conductor del vehículo ante las indicaciones que le hace el agente del vehículo policial con la señal V-1 encendida?',
      opciones: ['Reducir la marcha', 'Continuar la marcha', 'Detenerse en la zona adecuada'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'senales#vehiculos',
      explicacion: 'La señal V-1 de los vehículos policiales indica la orden de detenerse.',
    },
    {
      texto: 'En un accidente de tráfico se produce el efecto submarino cuando...',
      opciones: ['El cuerpo del ocupante del vehículo se desliza por debajo del cinturón', 'El reposacabezas no está bien regulado', 'El airbag se despliega sobre el cuerpo'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#cinturon',
      explicacion: 'El efecto submarino se produce cuando el cuerpo se desliza por debajo del cinturón de seguridad abdominal.',
    },
    {
      texto: 'En condiciones meteorológicas especialmente desfavorables, como un fuerte granizo, ¿qué precauciones, entre otras, debe adoptar?',
      opciones: ['Disminuir la velocidad y aumentar la distancia de seguridad', 'Frenar con fuerza y apagar el alumbrado', 'Detenerse en el carril de servicio'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#aquaplaning',
      explicacion: 'Ante condiciones desfavorables hay que moderar la velocidad y aumentar la distancia de seguridad.',
    },
    {
      texto: '¿Qué indica el panel situado bajo una señal de peligro?',
      opciones: ['La distancia al final de un tramo', 'La longitud de un tramo', 'La distancia al inicio de un tramo'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#peligro',
      explicacion: 'El panel bajo una señal de peligro indica la distancia desde el lugar hasta el inicio del tramo advertido.',
    },
    {
      texto: 'Si conduce de noche para evitar los atascos, debe tener en cuenta que...',
      opciones: ['El sueño o la somnolencia aparecen con mayor facilidad', 'No es necesario descansar en las zonas de servicio', 'La oscuridad evita la fatiga'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'Conducir de noche favorece la aparición de la somnolencia y la fatiga.',
    },
    // =====================
    // TEST OCTUBRE 2024
    // =====================
    {
      texto: 'Un conductor de una motocicleta, ¿puede circular por el arcén de una autovía?',
      opciones: ['No, está prohibido', 'Sí, si no hay carril bici', 'Solo si el arcén es transitable'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#carriles',
      explicacion: 'Las motocicletas no pueden circular por el arcén, salvo que esté expresamente permitido.',
    },
    {
      texto: 'Conducir durante mucho tiempo a una velocidad elevada...',
      opciones: ['Disminuye la aparición de la fatiga', 'Acelera la aparición de la fatiga y aumenta la agresividad', 'Acelera la aparición de la fatiga y nos reduce la agresividad'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'La velocidad elevada y la conducción prolongada aceleran la fatiga y aumentan la irascibilidad.',
    },
    {
      texto: 'Factores como la edad, la fatiga o el estado físico del conductor, ¿pueden hacer que los efectos secundarios de los medicamentos sean diferentes en cada persona?',
      opciones: ['Sí, pueden variar de una persona a otra', 'No, los efectos siempre son iguales', 'Solo si se modifica la dosis'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#medicamentos',
      explicacion: 'El efecto de los medicamentos varía según la edad, la fatiga o el estado físico de cada conductor.',
    },
    {
      texto: 'Si se lleva instalado un navegador GPS, hay que tener en cuenta que...',
      opciones: ['Las indicaciones del navegador tienen prioridad sobre el criterio del conductor', 'Puede apartar la vista seguidamente', 'No debe seguirse las indicaciones si contradigan la señalización'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#distracciones',
      explicacion: 'El navegador es solo una ayuda; el conductor no debe seguir indicaciones contrarias a la señalización de la vía.',
    },
    {
      texto: 'Se debe desactivar el airbag frontal instalado en el asiento del copiloto cuando...',
      opciones: ['Se instala un dispositivo de retención infantil orientado hacia atrás', 'Viaja una persona de taller pequeño', 'Hubo un accidente reciente'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#airbag',
      explicacion: 'El airbag debe desactivarse si se coloca un SRI orientado hacia atras, ya que podría provocar graves lesiones.',
    },
    {
      texto: 'En una autopista que transcurre por zona urbana, ¿a qué velocidad máxima puede circular un turismo si no existe señalización?',
      opciones: ['80 km/h', '120 km/h', '100 km/h'],
      indice_correcta: 0,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#autovia',
      explicacion: 'La velocidad máxima en vías urbanas es 80 km/h (en las vías urbanas y en las travesías, 50 km/h según la señalización).',
    },
    {
      texto: '¿Puede rebasar la velocidad máxima indicada en la señal?',
      opciones: ['Sí, para adelantar', 'No', 'Sí, cuando la vía no esté señalizada'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#minima',
      explicacion: 'Las señales de limitación de velocidad prohíben superar la velocidad indicada.',
    },
    {
      texto: 'Si, debido a la lluvia intensa, en una vía interurbana no distingue un vehículo de color negro a 50 metros, ¿puede circular con el alumbrado de largo alcance encendido?',
      opciones: ['No, está prohibido', 'Sí, porque la vía está insuficientemente iluminada', 'Solo si se usa también la luz antiniebla'],
      indice_correcta: 1,
      tema_slug: 'luces',
      dificultad: 2,
      referencia_manual: 'luces#tuneles',
      explicacion: 'En caso de lluvia intensa u otras condiciones de baja visibilidad en vía interurbana, se puede encender la luz de largo alcance, sin deslumbrar a otros conductores.',
    },
    {
      texto: 'La parte externa de uno de los neumáticos de su vehículo presenta una deformación en forma de bulto. ¿Es recomendable sustituir el neumático?',
      opciones: ['Sí, porque aumenta la posibilidad de sufrir un reventón', 'No, mientras no pierda aire', 'No, se puede reparar en un taller especializado'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#neumaticos',
      explicacion: 'Una deformación (bulto) en el flanco del neumático es signo de rotura interna y aumenta el riesgo de reventón.',
    },
    {
      texto: 'El agente balancea una luz amarilla verticalmente. ¿Qué indica?',
      opciones: ['Precaución al circular', 'Que se debe circular por el carril indicado', 'Que debe desviarse hacia la derecha'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#policia',
      explicacion: 'Cuando el agente balancea una luz amarilla indica precaución y obliga a reducir la velocidad.',
    },
    {
      texto: '¿Los carriles reversibles están delimitados por marcas viales?',
      opciones: ['Sí', 'No', 'Solo en diagonal'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#marcas-viales',
      explicacion: 'Los carriles reversibles se delimitan mediante marcas viales específicas que indican su funcionamiento.',
    },
    {
      texto: 'Conforme a los datos de accidentalidad, en los períodos de vacaciones y fines de semana...',
      opciones: ['No varía el número de accidentes con víctimas mortales', 'Aumenta el número de accidentes con víctimas mortales', 'Disminuye el número de accidentes con víctimas mortales'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#factores',
      explicacion: 'Las salidas y retornos, junto con la mayor afluencia (vacaciones y fines de semana), elevan el riesgo de accidentes mortales.',
    },
    {
      texto: 'Si su turismo ha pasado favorablemente la primera inspección técnica (ITV), ¿cuándo tiene que pasar la próxima inspección?',
      opciones: ['Dentro de 2 años', 'Dentro de 1 año', 'Dentro de 4 años'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#itv',
      explicacion: 'Tras la primera ITV (a los 4 años), la siguiente debe pasarse a los 2 años.',
    },
    // =====================
    // TEST MARZO 2026
    // =====================
    {
      texto: 'Esta señal de información que representa una flecha de cambio de sentido indica...',
      opciones: ['La proximidad de un lugar en el que se puede efectuar un cambio de sentido al mismo nivel', 'La proximidad de un lugar donde se puede cambiar de dirección', 'La dirección que los vehículos tienen obligación de seguir'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#indicacion',
      explicacion: 'La señal informa de un lugar donde se puede cambiar de sentido al mismo nivel con la calzada contraria.',
    },
    {
      texto: 'El conductor de una motocicleta, ¿tiene permitido realizar una parada en un carril reservado para autobuses?',
      opciones: ['Sí, mientras no obstaculice la circulación de autobuses', 'Está permitido parar, pero no estacionar', 'No, está prohibido'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#estacionamiento',
      explicacion: 'Los carriles reservados para autobuses prohíben tanto parar como estacionar.',
    },
    {
      texto: '¿Puede incorporarse a la circulación desde un estacionamiento circulando en marcha atrás?',
      opciones: ['Sí, si no invade un cruce de vías', 'No', 'Sí, siempre que su recorrido no sea superior a 20 metros'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#marcha-atras',
      explicacion: 'La marcha atrás puede usarse para incorporarse desde un estacionamiento, siempre que no invada cruces.',
    },
    {
      texto: 'Si tiene un accidente y no lleva puesto el cinturón de seguridad, en las posibilidades de resultar muerto...',
      opciones: ['Son mayores', 'Son menores', 'No varía'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#cinturon',
      explicacion: 'Sin el cinturón de seguridad, las posibilidades de morir en un accidente casi se duplican.',
    },
    {
      texto: 'En un turismo con nueve plazas, incluida la del conductor, ¿pueden viajar nueve menores de edad?',
      opciones: ['No, porque está superado el número de plazas autorizadas', 'Sí, siempre que sea en un turismo no colectivo', 'Sí, si son familiares'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#carga',
      explicacion: 'No se puede superar el número total de plazas autorizadas (que incluye al conductor).',
    },
    // =====================
    // TEST JUNIO 2026
    // =====================
    {
      texto: 'Circula con un turismo con remolque; ¿puede entrar en una vía con una señal que prohíbe la circulación de vehículos con remolque de un solo eje?',
      opciones: ['No, en ningún caso', 'Sí, si la M.M.A. del remolque no supera la indicada', 'Sí, si el remolque es ligero'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#prohibicion',
      explicacion: 'La señal prohíbe la entrada a vehículos con remolque de un solo eje, por lo que no puede circular por esa vía.',
    },
    {
      texto: 'El consumo de cannabis afecta a la conducción porque...',
      opciones: ['Aumenta la capacidad de concentración', 'Disminuye la somnolencia', 'Altera el tiempo de reacción y la capacidad de atención'],
      indice_correcta: 2,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#drogas',
      explicacion: 'El cannabis dilata el tiempo de reacción y degrada la atención y la coordinación.',
    },
    {
      texto: '¿Puede adelantar en un túnel con un solo carril para cada sentido?',
      opciones: ['Sí, si no es línea continua', 'No', 'Sí, si se tiene un semáforo que lo permite'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 2,
      referencia_manual: 'velocidad#tuneles',
      explicacion: 'En los túneles está prohibido adelantar al no poder disponer de la visión y seguridad necesaria.',
    },
    {
      texto: 'Si se ve obligado a circular con una rueda de repuesto de uso temporal o de emergencia, ¿qué debe tener en cuenta?',
      opciones: ['Que puede circular como con el resto a su máximo rendimiento', 'Las indicaciones del fabricante sobre presión y velocidad', 'Que su duración es igual que la de la rueda normal'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#neumaticos',
      explicacion: 'Las ruedas de repuesto de emergencia tienen limitaciones de velocidad y deben seguirse las indicaciones del fabricante.',
    },
    {
      texto: 'Estas marcas viales azules indican la zona...',
      opciones: ['De estacionamiento limitado en cuanto a duración', 'En que se puede estacionar ilimitadamente', 'En la que está prohibido estacionar'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#marcas-viales',
      explicacion: 'Las marcas azules indican zona de estacionamiento de duración limitada (zona azul).',
    },
    {
texto: 'En una vía urbana, ¿debe tocar el claxon para advertir que va a realizar un adelantamiento?',
      opciones: ['Sí, siempre que suene breve e intensamente', 'No', 'Sí, fuera del horario nocturno'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#advertencias-acusticas',
      explicacion: 'En vía urbana, el claxon solo puede usarse para evitar un accidente, no para el adelantamiento.',
    },
    {
      texto: 'Circula con la luz de largo alcance y se acerca a un vehículo que circula a menor velocidad en su mismo sentido. ¿Debe sustituir la luz de largo alcance por la de cruce?',
      opciones: ['Sí, para evitar deslumbrarlo', 'No', 'Solo si va a adelantarlo'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 2,
      referencia_manual: 'luces#larga',
      explicacion: 'Debe pasar a la luz de corto alcance para no deslumbro al vehículo que le precede.',
    },
    {
      texto: 'Si un conductor inicia un adelantamiento y se producen circunstancias que dificultan finalizar la maniobra...',
      opciones: ['Debe detener la maniobra y volver a su carril', 'Puede acelerar para terminar la maniobra', 'Debe proseguir la maniobra'],
      indice_correcta: 0,
      tema_slug: 'adelantamientos',
      dificultad: 2,
      referencia_manual: 'adelantamientos#reintegro',
      explicacion: 'Si surge peligro, hay que abandonar la maniobra y regresar a su carril cuando se pueda.',
    },
    {
      texto: '¿A qué velocidad máxima puede circular un ciclomotor por una carretera convencional?',
      opciones: ['80 km/h', '45 km/h', '60 km/h'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#ciclomotores',
      explicacion: 'Los ciclomotores no pueden superar los 45 km/h en ningún caso.',
    },
    {
      texto: '¿Cuál es una de las infracciones que cometen los conductores con mayor riesgo para los peatones?',
      opciones: ['No mantener la distancia de seguridad', 'No respetar la prioridad en los pasos para peatones', 'Circular con neumáticos lisos'],
      indice_correcta: 1,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#peatones',
      explicacion: 'No respetar la prioridad de los peatones en los pasos es una infracción grave que pone en riesgo su vida.',
    },
    {
      texto: '¿Quién está obligado a que los pasajeros mantengan la posición adecuada para garantizar su seguridad?',
      opciones: ['El conductor', 'Los pasajeros', 'Los pasajeros mayores de edad'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#carga',
      explicacion: 'El conductor es el responsable de velar por la posición y la seguridad de los pasajeros del vehículo.',
    },
    {
      texto: 'Si un vehículo de la policía de tráfico se sitúa detrás de usted y enciende un dispositivo con una luz roja destellante, ¿qué debe hacer?',
      opciones: ['Detenerse y seguir las instrucciones del agente', 'Continuar hasta un lugar seguro para detenerse', 'Continuar la marcha'],
      indice_correcta: 0,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#policia',
      explicacion: 'La señal de la policía obliga a detenerse y seguir las instrucciones de los agentes.',
    },
    {
      texto: '¿Es peligroso para un conductor que los rayos de sol caigan de forma directa sobre sus ojos?',
      opciones: ['No, siempre tener la vista iluminada ayuda', 'No, la luz ayuda', 'Sí, se ve la visibilidad reducida y dificulta ver la vía'],
      indice_correcta: 2,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'La luz directa del sol sobre los ojos reduce la visibilidad y aumenta el riesgo de accidente.',
    },
  ];

  let insertadas = 0;
  for (const p of preguntas) {
    const temaId = temaMap[p.tema_slug];
    if (!temaId) continue;
    if (selectExistente.get(p.texto)) continue;
    insertPregunta.run(p.texto, JSON.stringify(p.opciones), p.indice_correcta, temaId, p.dificultad, p.referencia_manual, p.explicacion, null);
    insertadas++;
  }

  db.prepare("INSERT INTO seed_meta (marca) VALUES ('preguntas_oficiales_v3')").run();
  console.log(`Seed oficial: ${insertadas} preguntas DGT insertadas`);
}