import { getDB } from './database';

export function ejecutarSeed(): void {
  const db = getDB();

  const numTemas = db.prepare('SELECT COUNT(*) as count FROM temas').get() as { count: number };
  if (numTemas.count > 0) return;

  const insertTema = db.prepare('INSERT INTO temas (nombre, slug, descripcion, orden) VALUES (?, ?, ?, ?)');
  const insertPregunta = db.prepare('INSERT INTO preguntas (texto, opciones, indice_correcta, tema_id, dificultad, referencia_manual, explicacion, imagen) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');

  const temas = [
    { nombre: 'Normas Generales', slug: 'normas-generales', descripcion: 'Principios básicos de circulación', orden: 1 },
    { nombre: 'Señales de Tráfico', slug: 'senales', descripcion: 'Señales verticales, marcas viales y semáforos', orden: 2 },
    { nombre: 'Velocidad', slug: 'velocidad', descripcion: 'Límites de velocidad y distancias', orden: 3 },
    { nombre: 'Adelantamientos', slug: 'adelantamientos', descripcion: 'Normas de adelantamiento y cruce', orden: 4 },
    { nombre: 'Prioridad', slug: 'prioridad', descripcion: 'Normas de prioridad de paso', orden: 5 },
    { nombre: 'Luces y Alumbrado', slug: 'luces', descripcion: 'Uso correcto del alumbrado', orden: 6 },
    { nombre: 'Alcohol y Conducción', slug: 'alcohol', descripcion: 'Alcohol, drogas y medicamentos', orden: 7 },
    { nombre: 'Seguridad Vial', slug: 'seguridad', descripcion: 'Cinturón, airbag, distancia de seguridad', orden: 8 },
  ];

  for (const t of temas) {
    insertTema.run(t.nombre, t.slug, t.descripcion, t.orden);
  }

  interface PreguntaSeed {
    texto: string;
    opciones: string[];
    indice_correcta: number;
    tema_slug: string;
    dificultad: number;
    referencia_manual?: string;
    explicacion?: string;
    imagen?: string;
  }

  const preguntas: PreguntaSeed[] = [
    // === NORMAS GENERALES ===
    { texto: '¿Qué debe hacer un conductor al aproximarse a un paso de peatones sin semáforo?', opciones: ['Aumentar la velocidad para pasar antes', 'Reducir la velocidad y estar preparado para detenerse', 'Tocar el claxon para advertir', 'Cambiar de carril'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 1, referencia_manual: 'normas-generales#peatones', explicacion: 'El conductor debe reducir la velocidad y estar preparado para detenerse ante un paso de peatones sin semáforo.' },
    { texto: '¿Está permitido estacionar en una curva?', opciones: ['Sí, siempre que no moleste', 'No, está prohibido', 'Sí, si se encienden las luces de emergencia', 'Solo de día'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 1, referencia_manual: 'normas-generales#estacionamiento', explicacion: 'Está prohibido estacionar en curvas y cambios de rasante por falta de visibilidad.' },
    { texto: '¿Cuál es la tasa máxima de alcohol permitida para conductores noveles?', opciones: ['0,5 g/l en sangre', '0,3 g/l en sangre', '0,8 g/l en sangre', '0,1 g/l en sangre'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 2, referencia_manual: 'alcohol#tasas', explicacion: 'Los conductores noveles tienen la tasa reducida: 0,3 g/l en sangre (0,15 mg/l en aire espirado).' },
    { texto: '¿Qué documento NO es obligatorio llevar en el coche?', opciones: ['Permiso de circulación', 'Ficha técnica del vehículo', 'Permiso de conducir', 'Recibo del seguro del año anterior'], indice_correcta: 3, tema_slug: 'normas-generales', dificultad: 1, referencia_manual: 'normas-generales#documentacion', explicacion: 'El recibo del seguro del año anterior no es necesario; basta con la documentación vigente.' },
    { texto: '¿Cuánto tiempo tiene un conductor novel para renovar el permiso?', opciones: ['5 años', '10 años', '2 años', 'Hasta los 65 años'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 2, referencia_manual: 'normas-generales#permiso', explicacion: 'Desde mayo de 2022 (Ley 18/2021), la primera renovación del permiso B se realiza a los 10 años, también para conductores noveles.' },
    { texto: 'En un cambio de sentido, ¿qué debemos hacer?', opciones: ['Hacerlo en cualquier lugar donde quepa el vehículo', 'Hacerlo donde la visibilidad sea suficiente y no esté prohibido', 'Siempre en una rotonda', 'Hacerlo marcha atrás'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 1, referencia_manual: 'normas-generales#cambio-sentido', explicacion: 'El cambio de sentido debe realizarse donde haya visibilidad suficiente y no esté expresamente prohibido.' },
    { texto: '¿Qué significa una línea continua en el borde de la calzada?', opciones: ['Que se puede aparcar', 'Que no se puede detener ni estacionar', 'Que es una zona de velocidad limitada', 'Que hay un carril bici'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 2, referencia_manual: 'normas-generales#marcas-viales', explicacion: 'La línea continua en el borde indica prohibición de detenerse y estacionar.' },
    { texto: '¿A qué distancia máxima del vehículo debe estar visible la placa de matrícula?', opciones: ['10 metros', '20 metros', '30 metros', '50 metros'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 3, referencia_manual: 'normas-generales#matricula', explicacion: 'La placa de matrícula debe ser legible a 20 metros de distancia.' },
    { texto: '¿Es obligatorio llevar el triángulo de preseñalización?', opciones: ['Sí, siempre', 'No, ya no es obligatorio', 'Solo en autopista', 'Solo de noche'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 1, referencia_manual: 'normas-generales#seguridad-vial', explicacion: 'Desde 2021 los triángulos ya no son obligatorios; se sustituyen por las luces V-16.' },
    { texto: '¿Cuándo debe un conductor utilizar las luces de emergencia?', opciones: ['Cuando va a mucha velocidad', 'Cuando el vehículo está inmóvil en la calzada o por emergencia', 'Cuando llueve', 'Al entrar en un túnel'], indice_correcta: 1, tema_slug: 'normas-generales', dificultad: 1, referencia_manual: 'normas-generales#emergencias', explicacion: 'Las luces de emergencia se usan cuando el vehículo está inmóvil en la calzada o en situación de emergencia.' },

    // === SEÑALES ===
    { texto: '¿Qué indica una señal circular de color azul con una flecha blanca hacia la derecha?', opciones: ['Sentido obligatorio hacia la derecha', 'Dirección recomendada', 'Fin de prohibición', 'Calle sin salida'], indice_correcta: 0, tema_slug: 'senales', dificultad: 1, referencia_manual: 'senales#obligacion', explicacion: 'Las señales circulares azules con flecha blanca son de obligación: indican la dirección que se debe seguir.', imagen: '/senales/r400.svg' },
    { texto: '¿Qué forma tiene una señal de "STOP"?', opciones: ['Circular', 'Triangular', 'Octogonal', 'Rectangular'], indice_correcta: 2, tema_slug: 'senales', dificultad: 1, referencia_manual: 'senales#stop', explicacion: 'La señal de STOP es la única con forma octogonal, lo que la hace reconocible incluso si está sucia.', imagen: '/senales/stop.svg' },
    { texto: '¿Qué significa una señal triangular con borde rojo y un ciervo en el centro?', opciones: ['Paso de animales domésticos', 'Paso de animales en libertad (ciervos)', 'Zona de caza', 'Reserva natural'], indice_correcta: 1, tema_slug: 'senales', dificultad: 1, referencia_manual: 'senales#peligro', explicacion: 'Señal de peligro por animales en libertad. Se encuentra en zonas con posible cruce de animales silvestres.', imagen: '/senales/p24.svg' },
    { texto: 'Una señal cuadrada de color azul con una flecha blanca indica:', opciones: ['Dirección obligatoria', 'Dirección recomendada', 'Autopista', 'Calle de sentido único'], indice_correcta: 1, tema_slug: 'senales', dificultad: 2, referencia_manual: 'senales#indicacion', explicacion: 'Las señales cuadradas azules son de indicación; la flecha blanca recomienda una dirección.', imagen: '/senales/s-direccion-recomendada.svg' },
    { texto: '¿Qué indica una señal redonda blanca con borde rojo y el número 60 en negro?', opciones: ['Velocidad mínima 60 km/h', 'Velocidad máxima 60 km/h', 'Fin de velocidad máxima 60 km/h', 'Recomendación de velocidad 60 km/h'], indice_correcta: 1, tema_slug: 'senales', dificultad: 1, referencia_manual: 'senales#reglamentacion', explicacion: 'Señal de prohibición: velocidad máxima limitada a 60 km/h.', imagen: '/senales/r301.svg' },
    { texto: '¿Qué significa una señal redonda azul con el número 30 en blanco?', opciones: ['Velocidad máxima 30 km/h', 'Velocidad mínima 30 km/h', 'Recomendación velocidad 30 km/h', 'Fin de velocidad mínima 30 km/h'], indice_correcta: 1, tema_slug: 'senales', dificultad: 2, referencia_manual: 'senales#obligacion', explicacion: 'Señal de obligación: velocidad mínima de 30 km/h.', imagen: '/senales/r412.svg' },
    { texto: '¿Qué indica una señal con forma de rombo de color amarillo?', opciones: ['Autopista', 'Carretera prioritaria', 'Carretera de montaña', 'Zona de obras'], indice_correcta: 1, tema_slug: 'senales', dificultad: 2, referencia_manual: 'senales#prioridad', explicacion: 'La señal de rombo amarillo indica "carretera prioritaria": los vehículos en esa vía tienen prioridad.', imagen: '/senales/r3.svg' },
    { texto: '¿Qué significa una señal de prohibido adelantar?', opciones: ['Prohibido adelantar a cualquier vehículo', 'Prohibido adelantar excepto motocicletas', 'Prohibido adelantar excepto si hay más de un carril', 'Prohibido adelantar a vehículos de más de 3.500 kg'], indice_correcta: 0, tema_slug: 'senales', dificultad: 1, referencia_manual: 'senales#prohibicion', explicacion: 'La señal prohíbe adelantar a cualquier vehículo que circule por la calzada.', imagen: '/senales/r302.svg' },
    { texto: 'Una señal de "Ceda el paso" tiene forma:', opciones: ['Circular', 'Triangular con punta hacia abajo', 'Octogonal', 'Rectangular'], indice_correcta: 1, tema_slug: 'senales', dificultad: 1, referencia_manual: 'senales#ceda', explicacion: 'La señal de "Ceda el paso" es un triángulo equilátero invertido (punta hacia abajo) con borde rojo.', imagen: '/senales/r1.svg' },
    { texto: '¿Qué indica una señal rectangular verde en autopista?', opciones: ['Dirección a poblaciones', 'Servicios cercanos', 'Información turística', 'Dirección a autopista'], indice_correcta: 0, tema_slug: 'senales', dificultad: 1, referencia_manual: 'senales#paneles', explicacion: 'Los panoles verdes en autopista indican dirección a poblaciones por autopista.' },
    { texto: '¿Qué indica una señal con el símbolo de una mano levantada?', opciones: ['Agencia de viajes', 'Paso de peatones', 'Zona peatonal', 'Policía'], indice_correcta: 2, tema_slug: 'senales', dificultad: 2, referencia_manual: 'senales#indicacion', explicacion: 'Señal de indicación de zona peatonal.' },
    { texto: 'Una señal de advertencia con un tractor significa:', opciones: ['Prohibido circular con tractor', 'Cruce con camino de tractores', 'Circulación lenta de vehículos agrícolas', 'Zona de labranza'], indice_correcta: 2, tema_slug: 'senales', dificultad: 1, referencia_manual: 'senales#peligro', explicacion: 'Advierte de la posible circulación de vehículos agrícolas que circulan a baja velocidad.' },

    // === VELOCIDAD ===
    { texto: '¿Cuál es la velocidad máxima genérica en autopista para turismos?', opciones: ['100 km/h', '110 km/h', '120 km/h', '130 km/h'], indice_correcta: 2, tema_slug: 'velocidad', dificultad: 1, referencia_manual: 'velocidad#autopista', explicacion: 'La velocidad máxima genérica en autopista y autovía para turismos es 120 km/h.' },
    { texto: '¿Cuál es la velocidad máxima en carretera convencional para turismos?', opciones: ['80 km/h', '90 km/h', '100 km/h', '110 km/h'], indice_correcta: 1, tema_slug: 'velocidad', dificultad: 1, referencia_manual: 'velocidad#carretera', explicacion: 'En carretera convencional, la velocidad máxima para turismos es 90 km/h.' },
    { texto: '¿Cuál es la velocidad máxima en vías urbanas?', opciones: ['30 km/h', '40 km/h', '50 km/h', '60 km/h'], indice_correcta: 2, tema_slug: 'velocidad', dificultad: 1, referencia_manual: 'velocidad#urbana', explicacion: 'La velocidad máxima genérica en vías urbanas es 50 km/h.' },
    { texto: '¿A qué velocidad máxima puede circular un turismo en una carretera convencional con arcén de 1,50 metros?', opciones: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'], indice_correcta: 0, tema_slug: 'velocidad', dificultad: 3, referencia_manual: 'velocidad#carretera', explicacion: 'Si el arcén mide menos de 1,50 m, la velocidad máxima es 90 km/h. Si mide 1,50 m o más, puede ser 100 km/h.' },
    { texto: '¿Cuál es la velocidad mínima en autopista?', opciones: ['40 km/h', '50 km/h', '60 km/h', '70 km/h'], indice_correcta: 2, tema_slug: 'velocidad', dificultad: 2, referencia_manual: 'velocidad#minima', explicacion: 'La velocidad mínima en autopista y autovía es 60 km/h.' },
    { texto: '¿A qué velocidad máxima puede circular un camión de más de 3.500 kg en autopista?', opciones: ['80 km/h', '90 km/h', '100 km/h', '110 km/h'], indice_correcta: 1, tema_slug: 'velocidad', dificultad: 2, referencia_manual: 'velocidad#camiones', explicacion: 'Los camiones de más de 3.500 kg tienen limitada la velocidad a 90 km/h en autopista.' },
    { texto: '¿Cuál es la distancia mínima de seguridad para no colisionar por alcance?', opciones: ['La que permita detener el vehículo completamente', '50 metros', '100 metros', 'La distancia que recorro en 2 segundos'], indice_correcta: 3, tema_slug: 'velocidad', dificultad: 2, referencia_manual: 'velocidad#distancia-seguridad', explicacion: 'La regla de los 2 segundos: distancia que se recorre en al menos 2 segundos al mismo ritmo.' },
    { texto: '¿Cuál es la velocidad máxima en una vía urbana con un solo carril por sentido?', opciones: ['20 km/h', '30 km/h', '40 km/h', '50 km/h'], indice_correcta: 1, tema_slug: 'velocidad', dificultad: 2, referencia_manual: 'velocidad#urbana-30', explicacion: 'Desde 2021, en vías urbanas con un solo carril por sentido la velocidad máxima es 30 km/h.' },
    { texto: '¿Cuál es la velocidad máxima al adelantar en carretera convencional?', opciones: ['La misma que la velocidad máxima de la vía', '20 km/h más que la velocidad del adelantado', 'Nunca más de 90 km/h', '20 km/h más que el adelantado sin superar 90 km/h si es carretera convencional'], indice_correcta: 3, tema_slug: 'velocidad', dificultad: 3, referencia_manual: 'velocidad#adelantamiento', explicacion: 'Al adelantar en carretera convencional se puede superar el límite en 20 km/h sin exceder 90 km/h.' },
    { texto: '¿Cuál es la velocidad máxima para un turismo en carretera convencional que no tenga arcén de 1,50 m?', opciones: ['80 km/h', '90 km/h', '100 km/h', '110 km/h'], indice_correcta: 1, tema_slug: 'velocidad', dificultad: 2, referencia_manual: 'velocidad#carretera', explicacion: 'Sin arcén de 1,50 m, la velocidad máxima es 90 km/h.' },

    // === ADELANTAMIENTOS ===
    { texto: '¿Está permitido adelantar en una curva sin visibilidad?', opciones: ['Sí, si el otro vehículo va muy lento', 'No, está prohibido', 'Solo si no vienen coches de frente', 'Sí, si se toca el claxon'], indice_correcta: 1, tema_slug: 'adelantamientos', dificultad: 1, referencia_manual: 'adelantamientos#prohibiciones', explicacion: 'Está prohibido adelantar en curvas y cambios de rasante con visibilidad reducida.' },
    { texto: '¿Qué debe hacer el conductor adelantado durante la maniobra?', opciones: ['Aumentar la velocidad', 'Mantener la velocidad o reducirla ligeramente', 'Indicar con el brazo', 'Detenerse'], indice_correcta: 1, tema_slug: 'adelantamientos', dificultad: 1, referencia_manual: 'adelantamientos#normas', explicacion: 'El conductor adelantado debe mantener la velocidad o reducirla ligeramente para facilitar el adelantamiento.' },
    { texto: '¿Está permitido adelantar a un ciclista dejando 1 metro de separación?', opciones: ['Sí, es suficiente', 'No, deben dejarse 1,5 metros', 'No, deben dejarse 2 metros', 'Solo si no hay tráfico en sentido contrario'], indice_correcta: 1, tema_slug: 'adelantamientos', dificultad: 2, referencia_manual: 'adelantamientos#ciclistas', explicacion: 'Al adelantar a ciclistas debe dejarse una separación mínima de 1,5 metros.' },
    { texto: '¿Se puede adelantar por la derecha en autopista?', opciones: ['Sí, siempre que sea seguro', 'No, está prohibido excepto si el vehículo de delante indica giro a la izquierda', 'Sí, en autopista está permitido', 'Solo si hay tres carriles'], indice_correcta: 1, tema_slug: 'adelantamientos', dificultad: 1, referencia_manual: 'adelantamientos#derecha', explicacion: 'Solo se puede adelantar por la derecha si el vehículo de delante ha indicado su intención de girar a la izquierda.' },
    { texto: '¿Es obligatorio señalizar un adelantamiento?', opciones: ['Sí, con el intermitente izquierdo', 'No, si ya se ve la intención', 'Solo si hay tráfico', 'Sí, con el claxon'], indice_correcta: 0, tema_slug: 'adelantamientos', dificultad: 1, referencia_manual: 'adelantamientos#senalizacion', explicacion: 'Todo adelantamiento debe señalizarse con el intermitente izquierdo con antelación.' },
    { texto: '¿Se puede adelantar en un paso de peatones?', opciones: ['Sí, si no hay peatones', 'No, está prohibido', 'Solo si el paso está sin semáforo', 'Sí, si el vehículo de delante está parado'], indice_correcta: 1, tema_slug: 'adelantamientos', dificultad: 2, referencia_manual: 'adelantamientos#prohibiciones', explicacion: 'Está prohibido adelantar en los pasos de peatones señalizados.' },
    { texto: '¿Cuándo está permitido adelantar por la derecha en vía urbana?', opciones: ['Nunca', 'Cuando el carril izquierdo esté ocupado', 'Cuando haya varios carriles y el de la izquierda esté congestionado', 'Siempre que haya espacio'], indice_correcta: 2, tema_slug: 'adelantamientos', dificultad: 2, referencia_manual: 'adelantamientos#derecha', explicacion: 'En vía urbana con varios carriles, si el de la izquierda está congestionado, se puede adelantar por la derecha.' },
    { texto: '¿Qué distancia lateral debe dejarse al adelantar a un peatón?', opciones: ['0,5 metros', '1 metro', '1,5 metros', 'La máxima posible dentro del carril'], indice_correcta: 1, tema_slug: 'adelantamientos', dificultad: 3, referencia_manual: 'adelantamientos#distancia', explicacion: 'Al adelantar a peatones debe dejarse una separación lateral de al menos 1 metro.' },
    { texto: 'En un adelantamiento, ¿cuándo debe reintegrarse el conductor a su carril?', opciones: ['Inmediatamente después de rebasar al vehículo', 'Cuando vea el vehículo adelantado en el espejo retrovisor', 'Cuando el vehículo adelantado le pite', 'Al finalizar la línea continua'], indice_correcta: 1, tema_slug: 'adelantamientos', dificultad: 2, referencia_manual: 'adelantamientos#reintegro', explicacion: 'Debe reintegrarse cuando vea el vehículo adelantado en el espejo retrovisor.' },
    { texto: '¿Está permitido adelantar en un túnel?', opciones: ['Sí, si hay buena visibilidad', 'No, salvo que haya más de un carril en el sentido de la marcha', 'Sí, siempre', 'No, nunca'], indice_correcta: 1, tema_slug: 'adelantamientos', dificultad: 2, referencia_manual: 'adelantamientos#tuneles', explicacion: 'En túneles solo se puede adelantar si hay más de un carril en el mismo sentido de la marcha.' },

    // === PRIORIDAD ===
    { texto: 'En un cruce sin señalizar, ¿quién tiene prioridad?', opciones: ['El vehículo que viene por la derecha', 'El vehículo que viene por la izquierda', 'El vehículo más grande', 'El vehículo que va más rápido'], indice_correcta: 0, tema_slug: 'prioridad', dificultad: 1, referencia_manual: 'prioridad#derecha', explicacion: 'En un cruce sin señalizar, tiene prioridad el vehículo que se aproxima por la derecha.' },
    { texto: '¿Quién tiene prioridad en una rotonda?', opciones: ['Los vehículos que entran', 'Los vehículos que ya están dentro', 'El vehículo que va más lento', 'El vehículo que viene por la derecha'], indice_correcta: 1, tema_slug: 'prioridad', dificultad: 1, referencia_manual: 'prioridad#rotondas', explicacion: 'En una rotonda, tienen prioridad los vehículos que ya están circulando dentro de ella.' },
    { texto: '¿Tienen prioridad los peatones en un paso de peatones?', opciones: ['Sí, siempre', 'No, los coches tienen prioridad', 'Solo si hay semáforo en verde para ellos', 'Solo en vías urbanas'], indice_correcta: 0, tema_slug: 'prioridad', dificultad: 1, referencia_manual: 'prioridad#peatones', explicacion: 'Los peatones tienen siempre prioridad en los pasos de peatones señalizados.' },
    { texto: '¿Quién tiene prioridad al subir una pendiente estrecha?', opciones: ['El que sube', 'El que baja', 'El que va más rápido', 'El que toca el claxon primero'], indice_correcta: 0, tema_slug: 'prioridad', dificultad: 2, referencia_manual: 'prioridad#pendientes', explicacion: 'En pendientes estrechas donde no puedan cruzarse, tiene prioridad el vehículo que sube.' },
    { texto: 'Un vehículo que sale de un estacionamiento, ¿tiene prioridad?', opciones: ['Sí, siempre', 'No, debe ceder el paso a los vehículos que circulan', 'Solo si señaliza', 'Sí, si va marcha atrás'], indice_correcta: 1, tema_slug: 'prioridad', dificultad: 1, referencia_manual: 'prioridad#estacionamiento', explicacion: 'Al salir de un estacionamiento debe cederse el paso a los vehículos que circulan por la vía.' },
    { texto: 'En una intersección con semáforo en amarillo fijo, ¿qué debe hacer?', opciones: ['Acelerar para pasar', 'Detenerse si es posible hacerlo con seguridad', 'Continuar igual', 'Tocar el claxon'], indice_correcta: 1, tema_slug: 'prioridad', dificultad: 1, referencia_manual: 'prioridad#semaforos', explicacion: 'El amarillo fijo indica que el semáforo va a pasar a rojo; debe detenerse si es seguro hacerlo.' },
    { texto: '¿Quién tiene prioridad en un estrechamiento sin señalizar?', opciones: ['El que primero llegue', 'El que ya haya entrado en el estrechamiento', 'El que vaya más despacio', 'El que venga por la derecha'], indice_correcta: 1, tema_slug: 'prioridad', dificultad: 2, referencia_manual: 'prioridad#estrechamientos', explicacion: 'En un estrechamiento sin señalizar, tiene prioridad el vehículo que ya haya entrado.' },
    { texto: '¿Deben ceder el paso los vehículos a los trenes en un paso a nivel?', opciones: ['Sí, siempre', 'No, los trenes deben esperar', 'Solo si hay barreras', 'Solo si viene el tren'], indice_correcta: 0, tema_slug: 'prioridad', dificultad: 1, referencia_manual: 'prioridad#paso-nivel', explicacion: 'Los vehículos deben ceder siempre el paso a los trenes en los pasos a nivel.' },
    { texto: '¿Tiene prioridad un vehículo de emergencia con señales luminosas?', opciones: ['Sí, siempre sobre cualquier vehículo', 'Solo en autopista', 'Solo si va a más de 100 km/h', 'No, debe respetar las señales'], indice_correcta: 0, tema_slug: 'prioridad', dificultad: 1, referencia_manual: 'prioridad#emergencias', explicacion: 'Los vehículos de emergencia con señales luminosas y acústicas tienen prioridad absoluta.' },
    { texto: 'En una calle con pendiente, ¿quién tiene prioridad si no caben dos vehículos?', opciones: ['El que baja', 'El que sube, salvo que el que baje pueda apartarse más fácilmente', 'El que va marcha atrás', 'El que toca primero el claxon'], indice_correcta: 1, tema_slug: 'prioridad', dificultad: 3, referencia_manual: 'prioridad#pendientes', explicacion: 'Tiene prioridad el que sube, excepto si el que baja puede apartarse más fácilmente.' },

    // === LUCES ===
    { texto: '¿Qué luces debe utilizar un vehículo al circular dentro de un túnel?', opciones: ['Luces de posición', 'Luces de cruce o carretera', 'Luces antiniebla', 'Luces de emergencia'], indice_correcta: 1, tema_slug: 'luces', dificultad: 1, referencia_manual: 'luces#tuneles', explicacion: 'En túneles deben encenderse las luces de cruce (o carretera si no hay más vehículos).' },
    { texto: '¿Cuándo es obligatorio usar las luces de cruce?', opciones: ['Solo de noche', 'Entre la puesta y la salida del sol, y en condiciones meteorológicas adversas', 'Solo cuando llueve', 'Siempre que el conductor lo considere necesario'], indice_correcta: 1, tema_slug: 'luces', dificultad: 1, referencia_manual: 'luces#cruce', explicacion: 'Las luces de cruce son obligatorias desde la puesta hasta la salida del sol y en condiciones adversas.' },
    { texto: '¿Qué luces se deben usar con niebla espesa?', opciones: ['Luces de carretera', 'Luces antiniebla delanteras y traseras', 'Solo luces de posición', 'Luces de emergencia'], indice_correcta: 1, tema_slug: 'luces', dificultad: 1, referencia_manual: 'luces#antiniebla', explicacion: 'Con niebla espesa deben usarse las luces antiniebla delanteras y traseras.' },
    { texto: '¿Está permitido usar las luces de largo alcance en ciudad?', opciones: ['Sí, siempre que sea necesario', 'No, está prohibido salvo en vías insuficientemente iluminadas', 'Sí, si no hay peatones', 'Solo en avenidas anchas'], indice_correcta: 1, tema_slug: 'luces', dificultad: 2, referencia_manual: 'luces#largas', explicacion: 'En ciudad solo pueden usarse luces de largo alcance si la vía está insuficientemente iluminada.' },
    { texto: '¿Cuándo debe cambiar de luces de carretera a cruce?', opciones: ['Cuando se aproxima otro vehículo', 'Cada 5 minutos', 'Al entrar en una curva', 'Nunca, las largas son mejores'], indice_correcta: 0, tema_slug: 'luces', dificultad: 1, referencia_manual: 'luces#cambio', explicacion: 'Debe cambiarse a luces de cruce cuando se aproxime otro vehículo en sentido contrario.' },
    { texto: '¿Qué luces son obligatorias en una motocicleta durante el día?', opciones: ['Ninguna', 'Luces de cruce (obligatorias 24h)', 'Luces de posición', 'Luces antiniebla'], indice_correcta: 1, tema_slug: 'luces', dificultad: 2, referencia_manual: 'luces#motos', explicacion: 'Las motocicletas deben circular siempre con las luces de cruce encendidas, incluso de día.' },
    { texto: '¿Qué indica la luz antiniebla trasera?', opciones: ['Que el vehículo está averiado', 'Que hay niebla o condiciones adversas', 'Que el vehículo va a girar', 'Que el vehículo frena'], indice_correcta: 1, tema_slug: 'luces', dificultad: 1, referencia_manual: 'luces#antiniebla-trasera', explicacion: 'La luz antiniebla trasera advierte de condiciones meteorológicas adversas como niebla, lluvia intensa o nieve.' },
    { texto: '¿Se pueden usar las luces de emergencia mientras se circula?', opciones: ['No, solo cuando el vehículo está parado', 'Sí, para advertir de un peligro inminente', 'Sí, siempre que se quiera', 'No, nunca'], indice_correcta: 1, tema_slug: 'luces', dificultad: 2, referencia_manual: 'luces#emergencias', explicacion: 'Las luces de emergencia pueden usarse en circulación para advertir de un peligro inminente.' },
    { texto: '¿Qué luces debe encender al circular marcha atrás?', opciones: ['Luces de posición', 'Luces de marcha atrás (blancas)', 'Luces antiniebla', 'Luces de cruce'], indice_correcta: 1, tema_slug: 'luces', dificultad: 1, referencia_manual: 'luces#marcha-atras', explicacion: 'Al circular marcha atrás se encienden automáticamente las luces blancas de marcha atrás.' },
    { texto: '¿Es obligatorio llevar las luces encendidas durante el día en autopista?', opciones: ['Sí, siempre', 'No, solo en condiciones adversas', 'Sí, en autopista es obligatorio', 'Solo para vehículos de menos de 3.500 kg'], indice_correcta: 1, tema_slug: 'luces', dificultad: 2, referencia_manual: 'luces#dia', explicacion: 'No es obligatorio llevar luces de día en autopista, excepto en condiciones adversas o para motocicletas.' },

    // === ALCOHOL Y CONDUCCIÓN ===
    { texto: '¿Cuál es la tasa máxima de alcohol en sangre para conductores con menos de 2 años de carnet?', opciones: ['0,5 g/l', '0,3 g/l', '0,8 g/l', '0,1 g/l'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 1, referencia_manual: 'alcohol#tasas', explicacion: 'Los conductores noveles (menos de 2 años) tienen la tasa máxima de 0,3 g/l en sangre.' },
    { texto: '¿Cuál es la tasa máxima de alcohol en aire espirado para conductores generales?', opciones: ['0,15 mg/l', '0,25 mg/l', '0,50 mg/l', '0,65 mg/l'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 2, referencia_manual: 'alcohol#tasas', explicacion: 'La tasa máxima general es 0,25 mg/l en aire espirado (0,5 g/l en sangre).' },
    { texto: '¿Conducir después de consumir drogas está...?', opciones: ['Permitido si no se nota el efecto', 'Prohibido en todo caso', 'Permitido en carreteras secundarias', 'Permitido si se ha dormido después'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 1, referencia_manual: 'alcohol#drogas', explicacion: 'Conducir bajo los efectos de drogas está siempre prohibido, independientemente de la cantidad.' },
    { texto: '¿Cuántas cervezas (5º) puede beber un conductor novel sin dar positivo?', opciones: ['Ninguna, su tasa es 0,3 g/l', '1 cerveza', '2 cervezas', '3 cervezas'], indice_correcta: 0, tema_slug: 'alcohol', dificultad: 1, referencia_manual: 'alcohol#recomendaciones', explicacion: 'La única tasa segura es 0,0. Para un novel, incluso una cerveza puede dar positivo.' },
    { texto: '¿Qué efecto tiene el alcohol en la conducción?', opciones: ['Mejora los reflejos', 'Aumenta el tiempo de reacción y reduce la visión', 'No afecta a conductores experimentados', 'Solo afecta si se mezcla con medicamentos'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 1, referencia_manual: 'alcohol#efectos', explicacion: 'El alcohol aumenta el tiempo de reacción, reduce el campo visual y disminuye la coordinación.' },
    { texto: '¿Cuál es la tasa máxima de alcohol en sangre para conductores profesionales?', opciones: ['0,5 g/l', '0,3 g/l', '0,2 g/l', '0,1 g/l'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 2, referencia_manual: 'alcohol#profesionales', explicacion: 'Los conductores profesionales tienen tasa reducida: 0,3 g/l en sangre (0,15 mg/l en aire).' },
    { texto: '¿Qué medicamentos pueden afectar a la conducción?', opciones: ['Solo los que contienen alcohol', 'Muchos: ansiolíticos, antihistamínicos, antidepresivos...', 'Ninguno, todos son seguros', 'Solo los que requieren receta'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 2, referencia_manual: 'alcohol#medicamentos', explicacion: 'Muchos medicamentos afectan a la conducción: ansiolíticos, antihistamínicos, antidepresivos, etc.' },
    { texto: '¿Después de cuánto tiempo se elimina completamente el alcohol de la sangre?', opciones: ['1 hora', 'Depende de la cantidad: aproximadamente 1 hora por cada copa', '30 minutos', 'Inmediatamente al dormir'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 3, referencia_manual: 'alcohol#eliminacion', explicacion: 'El cuerpo elimina aproximadamente 0,1-0,15 g/l por hora, pero varía según la persona.' },
    { texto: '¿Está permitido conducir con cualquier cantidad de alcohol si no se supera la tasa legal?', opciones: ['Sí, la ley lo permite', 'No recomendado: cualquier alcohol afecta', 'Solo si se ha comido antes', 'Sí, es seguro'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 1, referencia_manual: 'alcohol#recomendaciones', explicacion: 'Aunque no se supere la tasa legal, cualquier cantidad de alcohol afecta a la conducción.' },
    { texto: '¿Qué sanción conlleva superar la tasa de alcohol en más del doble?', opciones: ['Multa económica', 'Multa y retirada del carnet', 'Prisión', 'Solo un aviso'], indice_correcta: 1, tema_slug: 'alcohol', dificultad: 2, referencia_manual: 'alcohol#sanciones', explicacion: 'Superar el doble de la tasa permitida es delito penal: multa, retirada del carnet y posibles penas de prisión.' },

    // === SEGURIDAD VIAL ===
    { texto: '¿Es obligatorio el uso del cinturón de seguridad en vías urbanas?', opciones: ['Solo en autopista', 'Sí, siempre en todos los asientos', 'Solo en los asientos delanteros', 'Solo si el vehículo tiene airbag'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 1, referencia_manual: 'seguridad#cinturon', explicacion: 'El cinturón es obligatorio para todos los ocupantes en todas las vías.' },
    { texto: '¿A partir de qué altura puede un niño usar el cinturón de adulto?', opciones: ['1,20 metros', '1,35 metros', '1,50 metros', '1 metro'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 2, referencia_manual: 'seguridad#infantil', explicacion: 'Los niños de altura igual o superior a 1,35 m pueden usar el cinturón de adulto.' },
    { texto: '¿Qué es la distancia de reacción?', opciones: ['La distancia recorrida desde que se pisa el freno hasta que el coche se para', 'La distancia recorrida desde que se percibe el peligro hasta que se pisa el freno', 'La distancia entre dos vehículos', 'La distancia de frenado total'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 1, referencia_manual: 'seguridad#distancias', explicacion: 'Distancia de reacción: la que se recorre desde que se ve el peligro hasta que se acciona el freno.' },
    { texto: '¿Qué es el "efecto acordeón" en el tráfico?', opciones: ['Un tipo de frenada', 'Las retenciones por no mantener la distancia de seguridad y frenar bruscamente', 'El movimiento de los muelles del coche', 'Un adelantamiento en cadena'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 2, referencia_manual: 'seguridad#efecto-acordeon', explicacion: 'Si no se mantiene la distancia de seguridad, los frenazos en cadena generan retenciones.' },
    { texto: '¿Qué debe hacer si un neumático se pincha durante la marcha?', opciones: ['Frenar bruscamente', 'Sujetar firmemente el volante, no frenar brusco y reducir velocidad gradualmente', 'Acelerar para estabilizar', 'Apagar el motor'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 1, referencia_manual: 'seguridad#emergencias', explicacion: 'Ante un pinchazo: sujetar el volante, no frenar brusco, reducir velocidad gradualmente.' },
    { texto: '¿Cuánto aumenta la distancia de frenado si se duplica la velocidad?', opciones: ['Se duplica', 'Se cuadruplica', 'No varía', 'Aumenta un 50%'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 2, referencia_manual: 'seguridad#frenado', explicacion: 'La distancia de frenado aumenta proporcionalmente al cuadrado de la velocidad (x4 si se duplica).' },
    { texto: '¿Qué es el "guidado" de una motocicleta?', opciones: ['La aceleración', 'La oscilación de la dirección a baja velocidad', 'El frenado', 'El cambio de marchas'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 3, referencia_manual: 'seguridad#motos', explicacion: 'Guidado es la oscilación voluntaria del manillar a baja velocidad para mantener el equilibrio.' },
    { texto: '¿Cada cuánto tiempo se recomienda revisar la presión de los neumáticos?', opciones: ['Cada semana', 'Cada 15 días', 'Cada mes', 'Cada 3 meses'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 2, referencia_manual: 'seguridad#neumaticos', explicacion: 'Se recomienda revisar la presión de los neumáticos cada 15 días.' },
    { texto: '¿Qué es el aquaplaning?', opciones: ['Conducir sobre agua helada', 'Pérdida de contacto de los neumáticos con el asfalto por una capa de agua', 'Un tipo de frenada', 'Una técnica de conducción eficiente'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 1, referencia_manual: 'seguridad#aquaplaning', explicacion: 'Aquaplaning: los neumáticos pierden contacto con el asfalto al no evacuar el agua correctamente.' },
    { texto: '¿Cuál es la profundidad mínima del dibujo de los neumáticos?', opciones: ['1 mm', '1,6 mm', '2 mm', '3 mm'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 1, referencia_manual: 'seguridad#neumaticos', explicacion: 'La profundidad mínima legal del dibujo es 1,6 mm.' },
    { texto: '¿Qué indica la luz naranja del panel de instrumentos con forma de motor?', opciones: ['Que el motor está en marcha', 'Una avería en el motor o el sistema de emisiones', 'Que necesita combustible', 'Que el aceite está bajo'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 1, referencia_manual: 'seguridad#testigos', explicacion: 'La luz de avería del motor (naranja/amarilla) indica un problema en el motor o emisiones.' },
    { texto: '¿Es obligatorio llevar el airbag activado para circular?', opciones: ['Sí, siempre para todos los ocupantes', 'Solo el del conductor', 'No, es opcional', 'Solo en autopista'], indice_correcta: 1, tema_slug: 'seguridad', dificultad: 2, referencia_manual: 'seguridad#airbag', explicacion: 'El airbag del conductor es obligatorio y debe estar activado para circular.' },
  ];

  const temaMap: Record<string, number> = {};
  const temasDb = db.prepare('SELECT id, slug FROM temas').all() as any[];
  for (const t of temasDb) {
    temaMap[t.slug] = t.id;
  }

  for (const p of preguntas) {
    const temaId = temaMap[p.tema_slug];
    if (temaId) {
      insertPregunta.run(
        p.texto,
        JSON.stringify(p.opciones),
        p.indice_correcta,
        temaId,
        p.dificultad,
        p.referencia_manual || null,
        p.explicacion || null,
        p.imagen || null
      );
    }
  }
}
