import { getDB } from './database';

/**
 * Preguntas nuevas para llegar a 300+ preguntas únicas
 * Elimina duplicados y añade contenido nuevo
 */
export function seedPreguntasNuevas(): void {
  const db = getDB();

  // Idempotente: solo se ejecuta una vez
  const marca = db.prepare("SELECT 1 FROM seed_meta WHERE marca = 'preguntas_nuevas_v1'").get();
  if (marca) return;

  const temaMap: Record<string, number> = {};
  const temas = db.prepare('SELECT id, slug FROM temas').all() as { id: number; slug: string }[];
  for (const t of temas) {
    temaMap[t.slug] = t.id;
  }

  const insertPregunta = db.prepare(
    'INSERT INTO preguntas (texto, opciones, indice_correcta, tema_id, dificultad, referencia_manual, explicacion, imagen) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
  );

  // Preguntas nuevas sin duplicados
  const preguntasNuevas: Array<{
    texto: string;
    opciones: string[];
    indice_correcta: number;
    tema_slug: string;
    dificultad: number;
    referencia_manual: string;
    explicacion: string;
  }> = [
    // =============================================
    // NORMAS GENERALES - Preguntas nuevas
    // =============================================
    {
      texto: '¿Qué sanción conlleva el uso del teléfono móvil mientras se conduce?',
      opciones: ['100 € y 2 puntos', '200 € y 3 puntos', '200 € y 6 puntos', '500 € y 6 puntos'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#sanciones',
      explicacion: 'Usar el móvil conduciendo: 200 € y 6 puntos del carnet.',
    },
    {
      texto: '¿Está permitido conducir con calzado inadecuado como chanclas?',
      opciones: ['Sí, si se conduce despacio', 'No, el calzado debe permitir manejar los pedales correctamente', 'Solo en ciudad', 'Solo si hay pocos peatones'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#basicos',
      explicacion: 'El calzado debe permitir manejar los pedales con seguridad y precisión.',
    },
    {
      texto: '¿Cuánto tiempo puede permanecer un vehículo estacionado en la misma zona?',
      opciones: ['El tiempo que quiera', 'Máximo 48 horas si no hay limitación', 'Máximo 24 horas', 'Máximo 12 horas'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#estacionamiento',
      explicacion: 'Si no hay limitación horaria, máximo 48 horas en el mismo sitio.',
    },
    {
      texto: '¿Qué vehículos pueden circular por el arcén?',
      opciones: ['Todos los vehículos lentos', 'Solo ambulancias', 'Ciclistas, peatones y vehículos agrícolas', 'Ninguno excepto emergencias'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#arcen',
      explicacion: 'El arcén es para peatones, ciclistas y vehículos agrícolas.',
    },
    {
      texto: '¿Está permitido dejar el motor encendido mientras se estaciona?',
      opciones: ['Sí, si es poco tiempo', 'No, debe apagarse el motor', 'Solo en invierno', 'Solo si hay pasajeros'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#estacionamiento',
      explicacion: 'Al estacionar debe apagarse el motor para evitar contaminación y ruido.',
    },
    {
      texto: '¿Qué debe hacer si se encuentra con una ambulancia con señales luminosas?',
      opciones: ['Acelerar para apartarse', 'Facilitar el paso reduciendo velocidad', 'Seguir igual', 'Detenerse inmediatamente'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#emergencias',
      explicacion: 'Debe facilitarse el paso a vehículos de emergencia.',
    },
    {
      texto: '¿Se puede adelantar a un vehículo por la derecha en una autovía con tres carriles?',
      opciones: ['No, nunca', 'Solo si el vehículo va lento', 'Sí, si el carril izquierdo está ocupado y hay densidad', 'Sí, siempre'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#adelantamiento',
      explicacion: 'En autovía con tráfico denso se puede adelantar por la derecha.',
    },
    {
      texto: '¿Cuándo debe un conductor señalizar un cambio de dirección?',
      opciones: ['Solo si hay otros vehículos', 'Con la suficiente antelación antes de la maniobra', 'Al comenzar el giro', 'Después de mirar por el espejo'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#maniobras',
      explicacion: 'Toda maniobra debe señalizarse con antelación suficiente.',
    },
    {
      texto: '¿Qué documentos son obligatorios llevar en el vehículo?',
      opciones: ['Solo el permiso de conducir', 'Permiso de conducir, permiso de circulación y ficha técnica', 'Solo el permiso de circulación', 'El recibo del seguro'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#documentacion',
      explicacion: 'Son obligatorios: permiso de conducir, permiso de circulación y ficha técnica.',
    },
    {
      texto: '¿Cuántos puntos pierde un conductor novel por una infracción grave?',
      opciones: ['2 puntos', '3 puntos', '4 puntos', '6 puntos'],
      indice_correcta: 2,
      tema_slug: 'normas-generales',
      dificultad: 3,
      referencia_manual: 'normas-generales#puntos',
      explicacion: 'Las infracciones graves restan 4 puntos.',
    },
    {
      texto: '¿Está permitido circular con auriculares puestos?',
      opciones: ['Sí, si es manos libres', 'No, está prohibido salvo dispositivos manos libres integrados', 'Solo si es un oído', 'Solo en ciudad'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#movil',
      explicacion: 'Está prohibido conducir con auriculares, salvo dispositivos manos libres integrados.',
    },
    {
      texto: '¿Qué debe hacer antes de iniciar la marcha?',
      opciones: ['Arrancar directamente', 'Ajustar asiento, espejos y ponerte el cinturón', 'Poner la radio', 'Revisar el aceite'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 1,
      referencia_manual: 'normas-generales#basicos',
      explicacion: 'Antes de iniciar la marcha: ajustar asiento, espejos y cinturón.',
    },
    {
      texto: '¿Está permitido usar dispositivos GPS en la mano mientras se conduce?',
      opciones: ['Sí, siempre', 'No, solo integrados o montados en el salpicadero', 'Solo en autopista', 'Solo si se va despacio'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#dispositivos',
      explicacion: 'Solo se permiten GPS integrados o montados en el salpicadero.',
    },
    {
      texto: '¿Cuál es la tasa máxima de alcohol en sangre para conductores noveles?',
      opciones: ['0,5 g/l', '0,3 g/l', '0,8 g/l', '0,1 g/l'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'alcohol#tasas',
      explicacion: 'Los conductores noveles tienen la tasa máxima de 0,3 g/l.',
    },
    {
      texto: '¿Está permitido estacionar en un puente?',
      opciones: ['Sí, si no hay señal que lo prohíba', 'No, está prohibido', 'Solo de día', 'Solo si hay arcén'],
      indice_correcta: 1,
      tema_slug: 'normas-generales',
      dificultad: 2,
      referencia_manual: 'normas-generales#estacionamiento',
      explicacion: 'Está prohibido estacionar en puentes, pasos inferiores y túneles.',
    },

    // =============================================
    // SEÑALES - Preguntas nuevas
    // =============================================
    {
      texto: '¿Qué indica una señal rectangular marrón?',
      opciones: ['Información de autopista', 'Información turística o de interés', 'Información de servicios', 'Información de obras'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#turismo',
      explicacion: 'Las señales marrones indican lugares de interés turístico o cultural.',
    },
    {
      texto: 'Una línea amarilla discontinua en el borde de la calzada significa:',
      opciones: ['Prohibido estacionar', 'Prohibido detenerse', 'Carga y descarga', 'Parada de autobús'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#marcas-viales',
      explicacion: 'Línea amarilla discontinua = prohibido estacionar (pero se puede detener).',
    },
    {
      texto: 'Una línea amarilla continua en el borde significa:',
      opciones: ['Prohibido estacionar', 'Prohibido detenerse', 'Ni estacionar ni detenerse', 'Carga y descarga'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#marcas-viales',
      explicacion: 'Línea amarilla continua = prohibido detenerse y estacionar.',
    },
    {
      texto: '¿Qué indica un panel naranja reflectante en un vehículo?',
      opciones: ['Vehículo de emergencia', 'Transporte de mercancías peligrosas', 'Vehículo lento', 'Vehículo agrícola'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#paneles',
      explicacion: 'Panel naranja = mercancías peligrosas.',
    },
    {
      texto: '¿Qué indica una luz verde intermitente en un semáforo?',
      opciones: ['Que va a pasar a amarillo', 'Prioridad para emergencias', 'Paso permitido con precaución', 'Que el semáforo está averiado'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 3,
      referencia_manual: 'senales#semaforos',
      explicacion: 'Verde intermitente = semáforo fuera de servicio, extremar precaución.',
    },
    {
      texto: 'Las marcas viales de color azul indican:',
      opciones: ['Plazas de estacionamiento limitado', 'Estacionamiento para personas con movilidad reducida', 'Plazas de pago', 'Carril de aceleración'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 3,
      referencia_manual: 'senales#marcas-viales',
      explicacion: 'Marcas azules: estacionamiento para personas con discapacidad.',
    },
    {
      texto: '¿Qué significa la señal de "STOP" en un paso a nivel?',
      opciones: ['Detenerse obligatoriamente y reanudar si es seguro', 'Reducir la velocidad', 'Ceder el paso al tren', 'Continuar con precaución'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#stop',
      explicacion: 'STOP en paso a nivel: detenerse obligatoriamente.',
    },
    {
      texto: '¿Qué forma tienen las señales de servicios?',
      opciones: ['Triangular', 'Rectangular azul con símbolo blanco', 'Redonda', 'Octogonal'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#servicios',
      explicacion: 'Las señales de servicios son rectangulares azules con un símbolo blanco.',
    },
    {
      texto: 'Una señal con un círculo rojo y un camión significa:',
      opciones: ['Prohibido camiones', 'Prohibido adelantar a camiones', 'Prohibido camiones de más de 3.500 kg', 'Zona de carga'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#prohibicion',
      explicacion: 'Prohíbe la entrada a vehículos de mercancías de más de 3.500 kg.',
    },
    {
      texto: '¿Qué indica una señal con un símbolo de grifo (gasolinera)?',
      opciones: ['Prohibición de repostar', 'Gasolinera o estación de servicio', 'Taller mecánico', 'Centro de información'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#servicios',
      explicacion: 'Señal de servicio: estación de servicio o gasolinera.',
    },
    {
      texto: '¿Qué indica una señal de peligro con un semáforo?',
      opciones: ['Semáforo averiado', 'Proximidad de un semáforo', 'Prohibido el paso', 'Carril reservado'],
      indice_correcta: 1,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#peligro',
      explicacion: 'Advierte de la proximidad de un semáforo.',
    },
    {
      texto: 'Una señal con una bicicleta dentro de un círculo azul indica:',
      opciones: ['Carril bici de uso obligatorio', 'Prohibido bicicletas', 'Taller de bicicletas', 'Aparcamiento para bicis'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#obligacion',
      explicacion: 'Círculo azul con bicicleta = vía obligatoria para ciclistas.',
    },
    {
      texto: '¿Qué forma tiene la señal de "calle residencial"?',
      opciones: ['Rectangular azul con peatón, coche y pelota', 'Redonda azul', 'Triangular roja', 'Octogonal'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 3,
      referencia_manual: 'senales#indicacion',
      explicacion: 'Zona residencial: velocidad máxima 20 km/h.',
    },
    {
      texto: 'Una señal de prohibición con una motocicleta significa:',
      opciones: ['Prohibido circular con moto', 'Prohibido adelantar motos', 'Zona de motos', 'Prohibido aparcar motos'],
      indice_correcta: 0,
      tema_slug: 'senales',
      dificultad: 1,
      referencia_manual: 'senales#prohibicion',
      explicacion: 'Prohíbe la circulación de motocicletas.',
    },
    {
      texto: '¿Qué indica una señal con dos flechas, una roja a la izquierda y una blanca a la derecha?',
      opciones: ['Giro obligatorio a la derecha', 'Fin de prohibición de giro', 'Dirección prohibida a la izquierda, obligatorio a la derecha', 'Cruce de direcciones'],
      indice_correcta: 2,
      tema_slug: 'senales',
      dificultad: 2,
      referencia_manual: 'senales#prohibicion',
      explicacion: 'Flecha roja izquierda = prohibido; flecha blanca derecha = obligatorio.',
    },

    // =============================================
    // VELOCIDAD - Preguntas nuevas
    // =============================================
    {
      texto: '¿Cuál es la velocidad máxima en vía urbana con dos carriles por sentido?',
      opciones: ['30 km/h', '40 km/h', '50 km/h', '60 km/h'],
      indice_correcta: 2,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#urbana',
      explicacion: 'Vías urbanas con 2+ carriles por sentido: 50 km/h.',
    },
    {
      texto: '¿Cuál es la velocidad máxima para turismos en carretera con arcén de 1,5 m o más?',
      opciones: ['80 km/h', '90 km/h', '100 km/h', '110 km/h'],
      indice_correcta: 2,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#carretera',
      explicacion: 'Si el arcén es de 1,5 m o más, se puede circular a 100 km/h.',
    },
    {
      texto: '¿Cuál es la velocidad máxima para un autobús en autopista?',
      opciones: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#autobuses',
      explicacion: 'Autobuses: 100 km/h en autopista.',
    },
    {
      texto: '¿A qué velocidad máxima puede circular un turismo cuando llueve intensamente?',
      opciones: ['No hay límite especial', '100 km/h en autopista', 'La velocidad debe reducirse y adecuarse', '80 km/h siempre'],
      indice_correcta: 2,
      tema_slug: 'velocidad',
      dificultad: 1,
      referencia_manual: 'velocidad#condiciones-adversas',
      explicacion: 'Con lluvia intensa debe reducirse la velocidad.',
    },
    {
      texto: '¿Cuál es la velocidad máxima para vehículos de mercancías menores de 3.500 kg en autopista?',
      opciones: ['100 km/h', '110 km/h', '120 km/h', '90 km/h'],
      indice_correcta: 2,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#camiones',
      explicacion: 'Vehículos de mercancías < 3.500 kg: 120 km/h en autopista.',
    },
    {
      texto: '¿Qué velocidad máxima debe respetar un turismo en una carretera de montaña?',
      opciones: ['50 km/h', 'La velocidad máxima genérica o específica de la vía', '30 km/h', 'La que marque la señal'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 2,
      referencia_manual: 'velocidad#montana',
      explicacion: 'Respetar límites genéricos o específicos, adecuando a las condiciones.',
    },
    {
      texto: '¿Qué debe hacer un conductor que circula muy lento en autovía sin motivo?',
      opciones: ['Seguir a su ritmo', 'Circular al menos a 60 km/h o salirse de la vía', 'Aumentar a 120 km/h', 'Encender emergencias'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 3,
      referencia_manual: 'velocidad#minima',
      explicacion: 'Ir muy lento sin motivo es peligroso; debe salirse si no alcanza velocidad adecuada.',
    },
    {
      texto: '¿Cuántos metros equivale aproximadamente 1 segundo de reacción a 90 km/h?',
      opciones: ['15 metros', '20 metros', '25 metros', '30 metros'],
      indice_correcta: 2,
      tema_slug: 'velocidad',
      dificultad: 3,
      referencia_manual: 'velocidad#distancias',
      explicacion: '90 km/h = 25 m/s. En 1 segundo se recorren 25 metros.',
    },
    {
      texto: '¿Cuál es la velocidad máxima al adelantar en carretera convencional?',
      opciones: ['La misma que la velocidad máxima', '20 km/h más que el adelantado sin superar 90 km/h', 'Nunca más de 90 km/h', '20 km/h más sin límite'],
      indice_correcta: 1,
      tema_slug: 'velocidad',
      dificultad: 3,
      referencia_manual: 'velocidad#adelantamiento',
      explicacion: 'Al adelantar en carretera convencional: +20 km/h sin exceder 90 km/h.',
    },
    {
      texto: '¿Cuál es la velocidad máxima para un turismo en autovía de montaña?',
      opciones: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'],
      indice_correcta: 0,
      tema_slug: 'velocidad',
      dificultad: 3,
      referencia_manual: 'velocidad#autopista',
      explicacion: 'Autovía de montaña: la DGT puede limitar a 90 km/h.',
    },

    // =============================================
    // ADELANTAMIENTOS - Preguntas nuevas
    // =============================================
    {
      texto: '¿Se puede adelantar en un cambio de rasante con visibilidad?',
      opciones: ['Sí, si hay suficiente visibilidad', 'No, está prohibido siempre', 'Solo si no hay línea continua', 'Sí, pero con precaución'],
      indice_correcta: 0,
      tema_slug: 'adelantamientos',
      dificultad: 2,
      referencia_manual: 'adelantamientos#prohibiciones',
      explicacion: 'Se puede adelantar en cambio de rasante si hay visibilidad suficiente.',
    },
    {
      texto: '¿Cuándo debe señalizar el final del adelantamiento?',
      opciones: ['Al comenzar a reintegrarse', 'Antes de reintegrarse, con el intermitente derecho', 'Al rebasar el vehículo', 'No es necesario'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 1,
      referencia_manual: 'adelantamientos#senalizacion',
      explicacion: 'La reintegración debe señalizarse con el intermitente derecho.',
    },
    {
      texto: '¿Está permitido adelantar en un paso a nivel sin barreras?',
      opciones: ['Sí, si no viene el tren', 'No, está prohibido', 'Solo si hay visibilidad', 'Sí, en autopista'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 1,
      referencia_manual: 'adelantamientos#prohibiciones',
      explicacion: 'Está prohibido adelantar en pasos a nivel.',
    },
    {
      texto: '¿Puede un camión adelantar a otro camión en autopista?',
      opciones: ['Sí, siempre que sea seguro', 'Sí, pero con limitación de tiempo', 'No, los camiones no pueden adelantar', 'Solo si no hay tráfico'],
      indice_correcta: 0,
      tema_slug: 'adelantamientos',
      dificultad: 1,
      referencia_manual: 'adelantamientos#normas',
      explicacion: 'Los camiones pueden adelantar si es seguro.',
    },
    {
      texto: '¿Qué distancia lateral debe dejarse al adelantar a un ciclista en carretera?',
      opciones: ['1 metro', '1,5 metros', '2 metros', '0,5 metros'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 1,
      referencia_manual: 'adelantamientos#ciclistas',
      explicacion: '1,5 metros de separación lateral al adelantar ciclistas.',
    },
    {
      texto: 'Al adelantar a un grupo de ciclistas, ¿qué debe hacer?',
      opciones: ['Adelantar como a un vehículo', 'Reducir la velocidad y dejar 1,5 m', 'Tocar el claxon', 'Esperar detrás'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 2,
      referencia_manual: 'adelantamientos#ciclistas',
      explicacion: 'Reducir velocidad y dejar 1,5 m de separación.',
    },
    {
      texto: '¿Cuándo está permitido adelantar por la derecha en autopista?',
      opciones: ['Nunca', 'Cuando haya densidad de tráfico y todos los carriles estén ocupados', 'Siempre que sea seguro', 'Cuando el vehículo va lento'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 1,
      referencia_manual: 'adelantamientos#derecha',
      explicacion: 'Con tráfico denso, si todos los carriles están ocupados.',
    },
    {
      texto: '¿Cuánto tiempo puede ocupar el carril izquierdo un camión adelantando?',
      opciones: ['El tiempo necesario', 'Máximo 2 minutos', 'Máximo 3 minutos', 'No hay límite'],
      indice_correcta: 0,
      tema_slug: 'adelantamientos',
      dificultad: 2,
      referencia_manual: 'adelantamientos#normas',
      explicacion: 'Solo el tiempo necesario para adelantar.',
    },
    {
      texto: '¿Se puede adelantar en una intersección?',
      opciones: ['Sí, si no hay tráfico', 'No, salvo a ciclistas o en vía prioritaria', 'Sí, siempre que se señalice', 'Solo sin semáforo'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 2,
      referencia_manual: 'adelantamientos#prohibiciones',
      explicacion: 'No se puede adelantar en intersecciones, salvo a ciclistas o en vía prioritaria.',
    },
    {
      texto: '¿Qué distancia debe mantener al reintegrarse tras un adelantamiento?',
      opciones: ['Al menos 50 metros', 'La suficiente para ver al vehículo en el retrovisor', '5 metros', 'La distancia de frenado'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 1,
      referencia_manual: 'adelantamientos#reintegro',
      explicacion: 'Reintegrarse cuando se vea el vehículo en el espejo retrovisor.',
    },
    {
      texto: '¿Se puede adelantar a varios vehículos a la vez?',
      opciones: ['Sí, si hay suficiente visibilidad y espacio', 'No, solo uno a la vez', 'Solo en autopista', 'Solo si son ciclistas'],
      indice_correcta: 0,
      tema_slug: 'adelantamientos',
      dificultad: 2,
      referencia_manual: 'adelantamientos#normas',
      explicacion: 'Se puede adelantar a varios si hay visibilidad y espacio.',
    },
    {
      texto: '¿Está permitido adelantar a un peatón dejando 0,5 metros?',
      opciones: ['Sí, es suficiente', 'No, debe dejarse al menos 1 metro', 'No, 1,5 metros', 'La máxima posible'],
      indice_correcta: 1,
      tema_slug: 'adelantamientos',
      dificultad: 3,
      referencia_manual: 'adelantamientos#distancia',
      explicacion: 'Al menos 1 metro de separación lateral con peatones.',
    },

    // =============================================
    // PRIORIDAD - Preguntas nuevas
    // =============================================
    {
      texto: '¿Tienen prioridad los ciclistas en un carril bici?',
      opciones: ['Sí, deben ser respetados al cruzar una vía', 'No, deben ceder el paso', 'Solo si hay semáforo', 'Depende de la hora'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 2,
      referencia_manual: 'prioridad#ciclistas',
      explicacion: 'Los ciclistas en carril bici tienen prioridad.',
    },
    {
      texto: 'En un paso para peatones con semáforo, ¿cuándo deben detenerse los vehículos?',
      opciones: ['Siempre que haya peatones esperando', 'Cuando el semáforo esté en rojo para vehículos', 'Solo si el peatón levanta la mano', 'Cuando el peatón esté en el paso'],
      indice_correcta: 1,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#semaforos',
      explicacion: 'Con semáforo en rojo para vehículos.',
    },
    {
      texto: '¿Debe un vehículo ceder el paso a los peatones en una acera al girar?',
      opciones: ['Sí, al girar para entrar en una calle', 'No, los peatones deben esperar', 'Solo si hay paso de peatones', 'Depende de la velocidad'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 2,
      referencia_manual: 'prioridad#peatones',
      explicacion: 'Al girar, debe cederse el paso a los peatones.',
    },
    {
      texto: 'Un vehículo de vía de servicio, ¿tiene prioridad sobre el de la vía principal?',
      opciones: ['Sí, siempre', 'No, debe ceder el paso', 'Solo si es más grande', 'Depende de quién llegue primero'],
      indice_correcta: 1,
      tema_slug: 'prioridad',
      dificultad: 2,
      referencia_manual: 'prioridad#incorporaciones',
      explicacion: 'Los de vías de servicio deben ceder el paso.',
    },
    {
      texto: '¿Quién tiene prioridad al incorporarse desde un carril de aceleración?',
      opciones: ['El que se incorpora si señaliza', 'Los vehículos que ya circulan por la vía principal', 'El más rápido', 'El que está más adelantado'],
      indice_correcta: 1,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#incorporaciones',
      explicacion: 'Los que se incorporan deben ceder el paso.',
    },
    {
      texto: 'En un estrechamiento con un vehículo parado, ¿quién tiene prioridad?',
      opciones: ['El vehículo que circula', 'El vehículo parado si está averiado', 'Depende de quién llegó primero', 'El más grande'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 2,
      referencia_manual: 'prioridad#estrechamientos',
      explicacion: 'El que circula tiene prioridad sobre el parado.',
    },
    {
      texto: '¿Tienen prioridad los vehículos de transporte escolar al subir o bajar niños?',
      opciones: ['Sí, con señales luminosas activadas', 'No, deben cumplir normas generales', 'Solo en vías urbanas', 'Depende de la hora'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 2,
      referencia_manual: 'prioridad#escolar',
      explicacion: 'Con señales luminosas activadas tienen prioridad.',
    },
    {
      texto: 'En una intersección con STOP, ¿dónde debe detenerse?',
      opciones: ['En la línea de detención o antes de la incorporación', 'En medio del cruce', 'Detrás del vehículo detenido', 'Donde mejor vea'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#stop',
      explicacion: 'En la línea de detención o antes de la incorporación.',
    },
    {
      texto: '¿Quién tiene prioridad en una vía estrecha de montaña si dos vehículos se encuentran?',
      opciones: ['El que sube', 'El que baja', 'El que va más lento', 'El que está más cerca del ensanche'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#pendientes',
      explicacion: 'En pendientes estrechas, prioridad al que sube.',
    },
    {
      texto: '¿Está permitido bloquear un cruce aunque el semáforo esté en verde si hay atasco?',
      opciones: ['Sí, el semáforo da prioridad', 'No, no debe entrar si no puede despejarlo', 'Sí, si se toca el claxon', 'Depende de la hora'],
      indice_correcta: 1,
      tema_slug: 'prioridad',
      dificultad: 2,
      referencia_manual: 'prioridad#semaforos',
      explicacion: 'No debe entrarse en un cruce si no se puede despejar.',
    },
    {
      texto: 'En una rotonda, ¿qué carril debe usar para salir en la primera salida?',
      opciones: ['El carril exterior (derecho)', 'El interior', 'Cualquier carril', 'El central'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#rotondas',
      explicacion: 'Para la primera salida, carril derecho.',
    },
    {
      texto: 'Un vehículo de emergencia con señales luminosas, ¿tiene prioridad?',
      opciones: ['Sí, siempre sobre cualquier vehículo', 'Solo en autopista', 'Solo si va rápido', 'No, debe respetar señales'],
      indice_correcta: 0,
      tema_slug: 'prioridad',
      dificultad: 1,
      referencia_manual: 'prioridad#emergencias',
      explicacion: 'Prioridad absoluta con señales luminosas y acústicas.',
    },

    // =============================================
    // LUCES - Preguntas nuevas
    // =============================================
    {
      texto: '¿Qué luces debe usar con lluvia intensa y vehículos delante?',
      opciones: ['Luces de cruce y antiniebla delantera si es necesario', 'Luces de carretera', 'Solo antiniebla trasera', 'Luces de emergencia'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#cruce',
      explicacion: 'Luces de cruce y antiniebla delantera si es preciso.',
    },
    {
      texto: '¿Cuándo debe usar las luces antiniebla traseras?',
      opciones: ['Con niebla espesa, lluvia torrencial o nevada intensa', 'Siempre que llueve', 'Al anochecer', 'En autopista siempre'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#antiniebla-trasera',
      explicacion: 'Solo con niebla espesa, lluvia torrencial o nevada intensa.',
    },
    {
      texto: '¿Qué luces son obligatorias en un túnel largo?',
      opciones: ['Luces de cruce o carretera', 'Solo las de posición', 'Luces antiniebla', 'Ninguna si está iluminado'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#tuneles',
      explicacion: 'Luces de cruce o carretera en cualquier túnel.',
    },
    {
      texto: '¿Se pueden usar las luces de emergencia al estacionar en doble fila?',
      opciones: ['Sí, es obligatorio', 'No, no autorizan el estacionamiento ilegal', 'Solo si es menos de 2 minutos', 'Solo de noche'],
      indice_correcta: 1,
      tema_slug: 'luces',
      dificultad: 2,
      referencia_manual: 'luces#emergencias',
      explicacion: 'Las luces de emergencia no autorizan el estacionamiento irregular.',
    },
    {
      texto: '¿Cuándo debe usar el alumbrado de corto alcance durante el día?',
      opciones: ['En túneles, pasos inferiores y condiciones adversas', 'Solo al atardecer', 'En autovía siempre', 'Cuando llueve ligeramente'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#cruce',
      explicacion: 'En túneles, pasos inferiores y condiciones adversas.',
    },
    {
      texto: '¿Qué alumbrado debe encenderse al rebasar otro vehículo en vía estrecha de noche?',
      opciones: ['Luces de carretera', 'Luces de cruce para no deslumbrar', 'Luces antiniebla', 'Intermitentes'],
      indice_correcta: 1,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#cambio',
      explicacion: 'Usar luces de cruce para no deslumbrar.',
    },
    {
      texto: '¿Cuántas luces antiniebla traseras debe tener un turismo?',
      opciones: ['Una o dos', 'Dos obligatoriamente', 'Cuatro', 'Ninguna, es opcional'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 3,
      referencia_manual: 'luces#antiniebla-trasera',
      explicacion: 'Al menos una (y como máximo dos).',
    },
    {
      texto: '¿Qué luces son obligatorias en ciclomotores durante el día?',
      opciones: ['Ninguna', 'Luces de cruce (obligatorias 24h)', 'Luces de posición', 'Luces antiniebla'],
      indice_correcta: 1,
      tema_slug: 'luces',
      dificultad: 2,
      referencia_manual: 'luces#motos',
      explicacion: 'Ciclomotores y motocicletas: luces de cruce 24h.',
    },
    {
      texto: '¿Qué indica un semáforo con luz blanca en forma de peatón?',
      opciones: ['Paso de peatones', 'Zona peatonal', 'Semáforo para tranvías', 'Semáforo para ciclistas'],
      indice_correcta: 2,
      tema_slug: 'luces',
      dificultad: 3,
      referencia_manual: 'luces#semaforos-especiales',
      explicacion: 'Luces blancas con forma de peatón o raya son para tranvías.',
    },
    {
      texto: '¿Qué indica la luz roja en la parte trasera de un vehículo en movimiento?',
      opciones: ['Que está frenando', 'Luces antiniebla encendidas', 'Que da marcha atrás', 'Son los intermitentes'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#frenos',
      explicacion: 'Las luces de freno son rojas y se encienden al pisar el freno.',
    },
    {
      texto: '¿Se pueden usar las luces antiniebla delanteras sin niebla?',
      opciones: ['Sí, mejoran la visibilidad', 'No, solo con niebla, lluvia intensa o nieve', 'Sí, en autopista siempre', 'Solo en carretera'],
      indice_correcta: 1,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#antiniebla',
      explicacion: 'Solo con niebla, lluvia intensa, nevada o nubes de humo.',
    },
    {
      texto: '¿Cuál es la luz que más deslumbra?',
      opciones: ['Luces de carretera (largas)', 'Luces antiniebla traseras', 'Luces de cruce', 'Luces LED'],
      indice_correcta: 0,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#largas',
      explicacion: 'Las largas tienen máximo alcance y pueden deslumbrar.',
    },
    {
      texto: '¿Qué luces debe encender al circular marcha atrás?',
      opciones: ['Luces de posición', 'Luces de marcha atrás (blancas)', 'Luces antiniebla', 'Luces de cruce'],
      indice_correcta: 1,
      tema_slug: 'luces',
      dificultad: 1,
      referencia_manual: 'luces#marcha-atras',
      explicacion: 'Se encienden automáticamente las luces blancas de marcha atrás.',
    },

    // =============================================
    // ALCOHOL - Preguntas nuevas
    // =============================================
    {
      texto: '¿Qué hacer si ha bebido y tiene que conducir?',
      opciones: ['Esperar unas horas o no conducir', 'Beber café para contrarrestar', 'Ducharse con agua fría', 'Conducir despacio'],
      indice_correcta: 0,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#recomendaciones',
      explicacion: 'La única solución segura es esperar o no conducir.',
    },
    {
      texto: '¿Qué tasa de alcohol en aire espirado se considera delito penal?',
      opciones: ['0,25 mg/l', '0,50 mg/l o superior', '0,60 mg/l', '0,15 mg/l'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 2,
      referencia_manual: 'alcohol#sanciones',
      explicacion: 'A partir de 0,50 mg/l en aire espirado es delito.',
    },
    {
      texto: '¿Qué efectos tienen las drogas en la conducción?',
      opciones: ['Mejoran la concentración', 'Alteran la percepción, tiempo de reacción y coordinación', 'Solo afectan con alcohol', 'No afectan a corto plazo'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#drogas',
      explicacion: 'Alteran percepción, reflejos y capacidad de conducir.',
    },
    {
      texto: '¿Cuánto alcohol tiene aproximadamente una cerveza de 33 cl?',
      opciones: ['5-10 g', '10-15 g', '15-20 g', '20-25 g'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 3,
      referencia_manual: 'alcohol#contenido',
      explicacion: 'Una cerveza de 33 cl con 5º contiene unos 13 g de alcohol puro.',
    },
    {
      texto: '¿Conducir con resaca es peligroso?',
      opciones: ['Sí, los efectos del alcohol persisten', 'No, una vez dormido se elimina', 'Solo si se ha bebido mucho', 'No, si se desayuna bien'],
      indice_correcta: 0,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#resaca',
      explicacion: 'La resaca sigue afectando a la capacidad de conducir.',
    },
    {
      texto: '¿Cuántas horas se necesitan para eliminar 3 copas de vino?',
      opciones: ['3 horas', '6 horas aproximadamente', '12 horas', '24 horas'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 2,
      referencia_manual: 'alcohol#eliminacion',
      explicacion: '3 copas necesitan ~3 horas mínimo, pero varía según la persona.',
    },
    {
      texto: '¿Qué ocurre si se supera la tasa de alcohol en más del doble siendo novel?',
      opciones: ['Multa de 500€', 'Delito penal con prisión y retirada del carnet', 'Solo pérdida de puntos', 'Multa de 1000€'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 2,
      referencia_manual: 'alcohol#sanciones',
      explicacion: 'Superar el doble de la tasa es delito penal.',
    },
    {
      texto: '¿Puede un conductor negarse a la prueba de alcoholemia?',
      opciones: ['Sí, es un derecho', 'No, negarse es delito penal', 'Sí, pero con multa', 'Solo si tiene abogado'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 1,
      referencia_manual: 'alcohol#sanciones',
      explicacion: 'Negarse es delito penal (prisión de 6 meses a 1 año).',
    },
    {
      texto: '¿Pueden las bebidas "sin alcohol" dar positivo?',
      opciones: ['No, son seguras', 'Sí, algunas contienen hasta 0,9% de alcohol', 'Solo si se mezclan', 'Depende del metabolismo'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 3,
      referencia_manual: 'alcohol#sin-alcohol',
      explicacion: 'Pueden contener hasta 0,9% de alcohol.',
    },
    {
      texto: '¿Cuál es la tasa máxima de alcohol en sangre para conductores profesionales?',
      opciones: ['0,5 g/l', '0,3 g/l', '0,2 g/l', '0,1 g/l'],
      indice_correcta: 1,
      tema_slug: 'alcohol',
      dificultad: 2,
      referencia_manual: 'alcohol#profesionales',
      explicacion: 'Conductores profesionales: 0,3 g/l en sangre.',
    },

    // =============================================
    // SEGURIDAD VIAL - Preguntas nuevas
    // =============================================
    {
      texto: '¿Cuánto reduce el cinturón el riesgo de muerte en accidente?',
      opciones: ['Un 25%', 'Un 50% en asientos delanteros', 'Un 75%', 'No reduce significativamente'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#cinturon',
      explicacion: 'Reduce un 50% el riesgo de muerte en delanteros.',
    },
    {
      texto: '¿Qué distancia de seguridad debe mantener en condiciones normales?',
      opciones: ['La distancia recorrida en 2 segundos', '50 metros', '30 metros', 'La distancia en 1 segundo'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#distancias',
      explicacion: 'Regla de los 2 segundos.',
    },
    {
      texto: '¿Qué es el "punto ciego" de un vehículo?',
      opciones: ['El punto donde el airbag no protege', 'El ángulo que no se ve por los espejos', 'El espacio detrás del vehículo', 'La zona delantera del capó'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#puntos-ciegos',
      explicacion: 'La zona que no se ve por los espejos retrovisores.',
    },
    {
      texto: '¿Cuánto debe durar un viaje antes de hacer una pausa?',
      opciones: ['Cada 1 hora', 'Cada 2 horas o 200 km', 'No es necesario', 'Cada 4 horas'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'Parar cada 2 horas o 200 km.',
    },
    {
      texto: '¿Qué es la fatiga en la conducción?',
      opciones: ['Cansancio que reduce reacción y atención', 'Un tipo de sueño', 'Solo ocurre de noche', 'Es una enfermedad'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#fatiga',
      explicacion: 'Reduce reflejos y atención.',
    },
    {
      texto: '¿Cuál es la profundidad mínima del dibujo del neumático recomendada?',
      opciones: ['1,6 mm (legal)', 'Se recomienda cambiar a partir de 3 mm', '2 mm', 'No hay recomendación'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#neumaticos',
      explicacion: 'Cambiar a partir de 3 mm por seguridad.',
    },
    {
      texto: '¿Qué ocurre si un airbag se despliega con el asiento muy cerca?',
      opciones: ['Nada, está diseñado para eso', 'Puede causar lesiones graves (mínimo 25 cm)', 'Funciona igual', 'Se despliega más suave'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#airbag',
      explicacion: 'Mantener 25 cm de distancia con el volante.',
    },
    {
      texto: '¿Qué debe hacer si un neumático explosiona en autopista?',
      opciones: ['Frenar a fondo', 'Sujetar volante, no frenar brusco y reducir gradualmente', 'Acelerar', 'Apagar el motor'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#emergencias',
      explicacion: 'Sujetar volante, no frenar brusco, reducir suavemente.',
    },
    {
      texto: '¿Cada cuánto debe revisarse el nivel de aceite?',
      opciones: ['Cada semana', 'Cada mes', 'Cada 5000 km', 'Cada cambio de aceite'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#mantenimiento',
      explicacion: 'Revisar semanalmente o cada 1000 km.',
    },
    {
      texto: '¿Qué indica la luz roja del testigo de presión de aceite?',
      opciones: ['Que el aceite está bajo', 'Presión insuficiente, detenerse inmediatamente', 'Toca cambiar aceite', 'Motor caliente'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#testigos',
      explicacion: 'Detenerse de inmediato para evitar daños al motor.',
    },
    {
      texto: '¿Cuánto aumenta la distancia de frenado en vía mojada?',
      opciones: ['Se duplica', 'Puede duplicarse o más', 'Aumenta un 50%', 'No varía'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#frenado',
      explicacion: 'Puede duplicarse o incluso triplicarse.',
    },
    {
      texto: '¿Qué es el control de estabilidad (ESP)?',
      opciones: ['Sistema que evita perder el control', 'Sistema de frenada de emergencia', 'Regulador de velocidad', 'Sistema de airbags'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 2,
      referencia_manual: 'seguridad#esp',
      explicacion: 'Ayuda a mantener la trayectoria y evitar derrapes.',
    },
    {
      texto: '¿Cuál es la presión correcta de los neumáticos?',
      opciones: ['La indicada por el fabricante', 'La máxima del neumático', '2,5 bares siempre', 'Depende de la velocidad'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#neumaticos',
      explicacion: 'La recomendada por el fabricante.',
    },
    {
      texto: '¿Se pueden llevar niños en brazos en el asiento delantero?',
      opciones: ['Sí, con cinturón', 'No, está prohibido', 'Solo sin airbag', 'Solo en viajes cortos'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#infantil',
      explicacion: 'Prohibido. Deben ir en su SRI homologado.',
    },
    {
      texto: '¿Qué es el ABS?',
      opciones: ['Sistema antibloqueo de frenos', 'Sistema de airbags', 'Control de tracción', 'Asistente de arranque'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#abs',
      explicacion: 'Evita que las ruedas se bloqueen al frenar.',
    },
    {
      texto: '¿Qué es el "efecto suelo"?',
      opciones: ['La adherencia del vehículo al asfalto a alta velocidad', 'La distancia al suelo', 'Un tipo de suspensión', 'La resistencia al viento'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 3,
      referencia_manual: 'seguridad#aerodinamica',
      explicacion: 'La adherencia que se pierde a alta velocidad.',
    },
    {
      texto: '¿Cuándo debe usar el freno de mano?',
      opciones: ['Al estacionar para inmovilizar', 'Para frenar en emergencias', 'En pendientes al arrancar', 'En todas las paradas'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#freno-mano',
      explicacion: 'Para inmovilizar el vehículo al estacionar.',
    },
    {
      texto: '¿Qué debe hacer si encuentra un accidente en la carretera?',
      opciones: ['Parar y ayudar, señalizando el peligro', 'Seguir conduciendo', 'Tocar el claxon', 'Aparcar en la calzada'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#emergencias',
      explicacion: 'Parar, señalizar y ayudar si es posible.',
    },
    {
      texto: '¿Qué debe hacer antes de cambiar un neumático pinchado en carretera?',
      opciones: ['Colocar triángulos de preseñalización y luces V-16', 'Solo encender emergencias', 'Nada, cambiar rápido', 'Poner balizas móviles'],
      indice_correcta: 0,
      tema_slug: 'seguridad',
      dificultad: 1,
      referencia_manual: 'seguridad#emergencias',
      explicacion: 'Señalizar con triángulos y luces V-16.',
    },
    {
      texto: '¿Qué es el "guidado" de una motocicleta?',
      opciones: ['La aceleración', 'La oscilación del manillar a baja velocidad', 'El frenado', 'El cambio de marchas'],
      indice_correcta: 1,
      tema_slug: 'seguridad',
      dificultad: 3,
      referencia_manual: 'seguridad#motos',
      explicacion: 'Oscilación voluntaria del manillar para mantener equilibrio.',
    },
  ];

  // Insertar preguntas
  for (const p of preguntasNuevas) {
    const temaId = temaMap[p.tema_slug];
    if (temaId) {
      insertPregunta.run(
        p.texto,
        JSON.stringify(p.opciones),
        p.indice_correcta,
        temaId,
        p.dificultad,
        p.referencia_manual,
        p.explicacion,
        null
      );
    }
  }

  // Marcar seed como ejecutado
  db.prepare("INSERT OR IGNORE INTO seed_meta (marca) VALUES ('preguntas_nuevas_v1')").run();

  console.log(`✅ Seed de preguntas nuevas: ${preguntasNuevas.length} preguntas insertadas`);
}
