import { getDB } from './database';

export function seedPreguntasExtra(): void {
  const db = getDB();

  // Idempotente: se ejecuta una sola vez, marcado en seed_meta.
  // (Antes se guardaba por conteo >= 200, lo que duplicó 112 preguntas
  // cuando el seed base quedaba por debajo de ese umbral.)
  const marca = db.prepare("SELECT 1 FROM seed_meta WHERE marca = 'preguntas_extra_v1'").get();
  if (marca) return;

  const temaMap: Record<string, number> = {};
  const temas = db.prepare('SELECT id, slug FROM temas').all() as any[];
  for (const t of temas) {
    temaMap[t.slug] = t.id;
  }

  const insertPregunta = db.prepare(
    'INSERT INTO preguntas (texto, opciones, indice_correcta, tema_id, dificultad, referencia_manual, explicacion, imagen) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
  );

  const extras: any[] = [

    // === NORMAS GENERALES (+15) ===
    { t: '¿Qué debe hacer un conductor antes de iniciar la marcha?', o: ['Ajustar el asiento y los espejos y abrocharse el cinturón', 'Arrancar el motor directamente', 'Poner la radio', 'Revisar el aceite'], r: 0, s: 'normas-generales', d: 1, m: 'normas-generales#basicos', e: 'Antes de iniciar la marcha hay que ajustar asiento, espejos y ponerse el cinturón.' },
    { t: '¿Cuál es la tasa máxima de alcohol en sangre para conductores noveles?', o: ['0,5 g/l', '0,3 g/l', '0,8 g/l', '0,1 g/l'], r: 1, s: 'normas-generales', d: 2, m: 'alcohol#tasas', e: 'Noveles y profesionales: 0,3 g/l en sangre.' },
    { t: '¿Está permitido estacionar en un puente?', o: ['Sí, si no hay señal que lo prohíba', 'No, está prohibido', 'Solo de día', 'Solo si hay arcén'], r: 1, s: 'normas-generales', d: 2, m: 'normas-generales#estacionamiento', e: 'Está prohibido estacionar en puentes, pasos inferiores y túneles.' },
    { t: '¿Cuál es la sanción por usar el teléfono móvil mientras se conduce?', o: ['100 € y 2 puntos', '200 € y 6 puntos', '500 € y 6 puntos', '300 € y 4 puntos'], r: 1, s: 'normas-generales', d: 2, m: 'normas-generales#sanciones', e: 'Usar el móvil conduciendo: 200 € y 6 puntos del carnet.' },
    { t: '¿Se puede conducir con auriculares?', o: ['Sí, si es manos libres', 'No, está prohibido', 'Sí, si solo es un oído', 'Sí, en ciudad'], r: 1, s: 'normas-generales', d: 1, m: 'normas-generales#basicos', e: 'Está prohibido conducir con auriculares, salvo dispositivos manos libres.' },
    { t: '¿Cuántos puntos pierde un conductor novel por una infracción grave?', o: ['2 puntos', '3 puntos', '4 puntos', '6 puntos'], r: 2, s: 'normas-generales', d: 3, m: 'normas-generales#puntos', e: 'Las infracciones graves restan 4 puntos; las muy graves, 6.' },
    { t: '¿Qué documentación debe llevar todo conductor?', o: ['Permiso de conducir, permiso de circulación y ficha técnica', 'Solo el permiso de conducir', 'Solo el permiso de circulación', 'El recibo del seguro'], r: 0, s: 'normas-generales', d: 1, m: 'normas-generales#documentacion', e: 'Son obligatorios: permiso de conducir, permiso de circulación y ficha técnica.' },
    { t: '¿Qué vehículos pueden circular por el arcén?', o: ['Ninguno, excepto en caso de emergencia', 'Ciclistas, peatones y vehículos agrícolas', 'Todos los vehículos lentos', 'Solo ambulancias'], r: 1, s: 'normas-generales', d: 2, m: 'normas-generales#arcen', e: 'El arcén es para peatones, ciclistas y vehículos agrícolas. Los turismos no deben circular por él.' },
    { t: '¿Está permitido dejar el motor encendido mientras se estaciona?', o: ['Sí, si es por poco tiempo', 'No, debe apagarse el motor', 'Sí, en invierno para la calefacción', 'Solo si hay otros pasajeros'], r: 1, s: 'normas-generales', d: 1, m: 'normas-generales#estacionamiento', e: 'Al estacionar debe apagarse el motor para evitar contaminación y ruido.' },
    { t: '¿Cuánto tiempo puede permanecer un vehículo en el mismo lugar de estacionamiento?', o: ['El tiempo que quiera si no hay señal', 'Máximo 48 horas si no hay limitación horaria', 'Máximo 24 horas', 'Máximo 12 horas'], r: 1, s: 'normas-generales', d: 3, m: 'normas-generales#estacionamiento', e: 'Si no hay limitación horaria, máximo 48 horas en el mismo sitio.' },
    { t: '¿Qué debe hacer si se encuentra con una ambulancia con señales luminosas?', o: ['Acelerar para apartarse', 'Facilitar el paso reduciendo velocidad o apartándose', 'Seguir igual, ella se apartará', 'Detenerse inmediatamente'], r: 1, s: 'normas-generales', d: 1, m: 'normas-generales#emergencias', e: 'Debe facilitarse el paso a vehículos de emergencia.' },
    { t: '¿Se puede adelantar a un vehículo por la derecha en una autovía con tres carriles?', o: ['Sí, si el carril izquierdo está ocupado y hay densidad de tráfico', 'No, nunca', 'Solo si el vehículo va a menos de 80 km/h', 'Sí, siempre'], r: 0, s: 'normas-generales', d: 2, m: 'normas-generales#adelantamiento', e: 'En autovía con tráfico denso se puede adelantar por la derecha.' },
    { t: '¿Cuándo debe un conductor señalizar un cambio de dirección?', o: ['Solo si hay otros vehículos cerca', 'Con la suficiente antelación antes de la maniobra', 'Al comenzar el giro', 'Después de mirar por el espejo'], r: 1, s: 'normas-generales', d: 1, m: 'normas-generales#maniobras', e: 'Toda maniobra debe señalizarse con antelación suficiente.' },
    { t: '¿Está permitido conducir con chanclas o calzado inadecuado?', o: ['Sí, cualquier calzado es válido', 'No, el calzado debe permitir manejar los pedales correctamente', 'Solo si son zapatos planos', 'Sí, si se conduce despacio'], r: 1, s: 'normas-generales', d: 1, m: 'normas-generales#basicos', e: 'El calzado debe permitir manejar los pedales con seguridad y precisión.' },

    // === SEÑALES (+20) ===
    { t: 'Una señal de peligro con un símbolo de dos flechas curvas opuestas indica:', o: ['Curva peligrosa a la derecha', 'Curvas próximas (curva y contra curva)', 'Calzada deslizante', 'Doble sentido'], r: 1, s: 'senales', d: 2, m: 'senales#peligro', e: 'Dos flechas curvas opuestas = curvas próximas (primera a la derecha).', img: '/senales/curvas-derecha.svg' },
    { t: '¿Qué indica una señal de prohibición con el número 80 y la palabra "FIN"?', o: ['Velocidad máxima 80 km/h', 'Fin de la prohibición de velocidad máxima 80 km/h', 'Velocidad mínima 80 km/h', 'Fin de la autopista'], r: 1, s: 'senales', d: 1, m: 'senales#reglamentacion', e: 'Señal de fin de prohibición: ya no hay límite de velocidad máxima.' },
    { t: '¿Qué forma tienen las señales de servicios?', o: ['Triangular', 'Rectangular azul con símbolo blanco', 'Redonda', 'Octogonal'], r: 1, s: 'senales', d: 2, m: 'senales#indicacion', e: 'Las señales de servicios son rectangulares azules con un símbolo blanco.' },
    { t: 'Una señal con un símbolo de grifo (gasolinera) es de tipo:', o: ['Peligro', 'Prohibición', 'Servicio', 'Obligación'], r: 2, s: 'senales', d: 1, m: 'senales#servicios', e: 'Las señales de servicio indican estaciones de servicio, restaurantes, hoteles, etc.', img: '/senales/s11.svg' },
    { t: '¿Qué indica una señal rectangular marrón?', o: ['Información de autopista', 'Información turística o de interés', 'Información de servicios', 'Información de obras'], r: 1, s: 'senales', d: 2, m: 'senales#turismo', e: 'Las señales marrones indican lugares de interés turístico o cultural.' },
    { t: '¿Qué significa una señal con un círculo rojo y una barra blanca horizontal?', o: ['Prohibido el paso', 'Prohibido girar a la derecha', 'Prohibido aparcar', 'Prohibido adelantar'], r: 0, s: 'senales', d: 1, m: 'senales#prohibicion', e: 'Círculo rojo con barra blanca = entrada prohibida.', img: '/senales/r100.svg' },
    { t: 'Una línea amarilla discontinua en el borde de la calzada significa:', o: ['Prohibido estacionar', 'Prohibido detenerse', 'Carga y descarga', 'Parada de autobús'], r: 0, s: 'senales', d: 2, m: 'senales#marcas-viales', e: 'Línea amarilla discontinua = prohibido estacionar (pero se puede detener).' },
    { t: 'Una línea amarilla continua en el borde significa:', o: ['Prohibido estacionar', 'Prohibido detenerse', 'Ni estacionar ni detenerse', 'Carga y descarga permitida'], r: 2, s: 'senales', d: 2, m: 'senales#marcas-viales', e: 'Línea amarilla continua = prohibido detenerse y estacionar.' },
    { t: '¿Qué indica una flecha blanca hacia arriba sobre fondo azul en una señal cuadrada?', o: ['Dirección obligatoria recto', 'Calle de sentido único', 'Recomendación de seguir recto', 'Autopista'], r: 2, s: 'senales', d: 3, m: 'senales#indicacion', e: 'Señal cuadrada azul con flecha arriba = recomendación de seguir recto.', img: null },
    { t: '¿Qué significa la señal de "STOP" en un paso a nivel?', o: ['Detenerse obligatoriamente y solo reanudar si es seguro', 'Reducir la velocidad', 'Ceder el paso al tren', 'Continuar con precaución'], r: 0, s: 'senales', d: 1, m: 'senales#stop', e: 'STOP en paso a nivel: detenerse obligatoriamente y reanudar solo si es seguro.', img: '/senales/stop.svg' },
    { t: 'Una señal de peligro con un símbolo de un semáforo indica:', o: ['Que hay un semáforo en rojo', 'Proximidad de un semáforo', 'Que el semáforo está averiado', 'Zona de semáforos'], r: 1, s: 'senales', d: 1, m: 'senales#peligro', e: 'Advierte de la proximidad de un semáforo.', img: '/senales/p3.svg' },
    { t: 'Una señal con una bicicleta dentro de un círculo azul indica:', o: ['Carril bici de uso obligatorio', 'Prohibido bicicletas', 'Taller de bicicletas', 'Zona de aparcamiento para bicis'], r: 0, s: 'senales', d: 1, m: 'senales#obligacion', e: 'Círculo azul con bicicleta = vía obligatoria para ciclistas.', img: '/senales/r407a.svg' },
    { t: 'Una señal de prohibición con una motocicleta significa:', o: ['Prohibido circular con moto', 'Prohibido adelantar motos', 'Zona de motos', 'Prohibido aparcar motos'], r: 0, s: 'senales', d: 1, m: 'senales#prohibicion', e: 'Prohíbe la circulación de motocicletas.', img: '/senales/r104.svg' },
    { t: '¿Qué indica un panel naranja reflectante en un vehículo?', o: ['Vehículo de emergencia', 'Transporte de mercancías peligrosas', 'Vehículo lento', 'Vehículo agrícola'], r: 1, s: 'senales', d: 2, m: 'senales#paneles', e: 'Panel naranja = mercancías peligrosas. Números: materia peligrosa y sustancia.' },
    { t: '¿Qué indica una señal de peligro con un símbolo de un coche cayendo al agua?', o: ['Peligro de inundación', 'Proximidad de un embarcadero', 'Proximidad de un tramo de vía inundable', 'Paso de vehículos anfibios'], r: 0, s: 'senales', d: 3, m: 'senales#peligro', e: 'Advierte de un tramo de vía que puede inundarse.' },
    { t: '¿Qué forma tiene la señal de "calle residencial"?', o: ['Rectangular azul con peatón, coche y pelota', 'Redonda azul', 'Triangular roja', 'Octogonal'], r: 0, s: 'senales', d: 3, m: 'senales#indicacion', e: 'Zona residencial: velocidad máxima 20 km/h, peatones tienen prioridad.', img: '/senales/s29.svg' },
    { t: 'Una señal con un círculo rojo y un camión significa:', o: ['Prohibido camiones', 'Prohibido adelantar a camiones', 'Prohibido camiones de más de 3.500 kg', 'Zona de carga y descarga'], r: 0, s: 'senales', d: 1, m: 'senales#prohibicion', e: 'Señal de prohibición de circulación para camiones.', img: '/senales/r106.svg' },
    { t: '¿Qué indica una señal con dos flechas, una roja hacia la izquierda y una blanca hacia la derecha?', o: ['Giro obligatorio a la derecha', 'Fin de prohibición de giro a la izquierda', 'Dirección prohibida a la izquierda, obligatorio a la derecha', 'Cruce de direcciones'], r: 2, s: 'senales', d: 2, m: 'senales#prohibicion', e: 'Flecha roja izquierda = prohibido girar a la izquierda; flecha blanca derecha = obligatorio girar a la derecha.', img: '/senales/r303.svg' },
    { t: 'Las marcas viales de color azul indican:', o: ['Plazas de estacionamiento con limitación de horario', 'Estacionamiento para personas con movilidad reducida', 'Plazas de pago', 'Carril de aceleración'], r: 1, s: 'senales', d: 3, m: 'senales#marcas-viales', e: 'Marcas azules: estacionamiento para personas con discapacidad.' },
    { t: '¿Qué indica una luz verde intermitente en un semáforo?', o: ['Que va a pasar a amarillo', 'Prioridad para vehículos de emergencia', 'Que el semáforo está averiado', 'Paso permitido con precaución'], r: 2, s: 'senales', d: 3, m: 'senales#semaforos', e: 'Verde intermitente = semáforo fuera de servicio o averiado, extremar precaución.' },

    // === VELOCIDAD (+15) ===
    { t: '¿A qué velocidad máxima puede circular un turismo con remolque en autopista?', o: ['120 km/h', '100 km/h', '90 km/h', '80 km/h'], r: 3, s: 'velocidad', d: 2, m: 'velocidad#remolque', e: 'Turismo con remolque: 80 km/h en autopista. MMA remolque &lt;= 750 kg: 90 km/h, &gt; 750 kg: 80 km/h.' },
    { t: '¿Cuál es la velocidad máxima para una motocicleta en autopista?', o: ['100 km/h', '110 km/h', '120 km/h', '130 km/h'], r: 2, s: 'velocidad', d: 1, m: 'velocidad#autopista', e: 'Las motos tienen el mismo límite que los turismos: 120 km/h en autopista.' },
    { t: '¿Cuál es la velocidad máxima en vía urbana con plataforma única?', o: ['10 km/h', '20 km/h', '30 km/h', '40 km/h'], r: 1, s: 'velocidad', d: 2, m: 'velocidad#urbana-20', e: 'Plataforma única de calzada y acera: 20 km/h.' },
    { t: '¿A qué velocidad máxima puede circular un autobús en autopista?', o: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'], r: 1, s: 'velocidad', d: 2, m: 'velocidad#autobuses', e: 'Autobuses: 100 km/h en autopista, 90 km/h en carretera convencional.' },
    { t: '¿Cuál es la velocidad máxima para un vehículo de mercancías de menos de 3.500 kg en autopista?', o: ['100 km/h', '110 km/h', '120 km/h', '90 km/h'], r: 2, s: 'velocidad', d: 2, m: 'velocidad#camiones', e: 'Vehículos de mercancías &lt; 3.500 kg: 120 km/h en autopista.' },
    { t: '¿Qué velocidad máxima debe respetar un turismo en una carretera de montaña?', o: ['50 km/h', 'La velocidad máxima genérica de la vía, ajustándose a las condiciones', '30 km/h', 'La que marque la señal específica'], r: 1, s: 'velocidad', d: 2, m: 'velocidad#montaña', e: 'Hay que respetar límites genéricos o específicos, pero siempre adecuando la velocidad a las condiciones.' },
    { t: '¿A qué velocidad máxima puede circular un turismo cuando llueve intensamente?', o: ['No hay límite especial, solo precaución', '100 km/h en autopista', 'La velocidad debe reducirse y adecuarse a las condiciones', '80 km/h en todas las vías'], r: 2, s: 'velocidad', d: 1, m: 'velocidad#condiciones-adversas', e: 'Con lluvia intensa debe reducirse la velocidad y aumentar la distancia de seguridad.' },
    { t: '¿Qué debe hacer un conductor que circula a 70 km/h en una autovía limitada a 120 km/h?', o: ['Seguir a 70 km/h si lo desea', 'Circular al menos a 60 km/h, pero si no hay razón para ir tan lento, debe salirse de la vía', 'Aumentar a 120 km/h obligatoriamente', 'Encender las luces de emergencia'], r: 1, s: 'velocidad', d: 3, m: 'velocidad#minima', e: 'Ir muy lento sin motivo también es peligroso. Si no se alcanza velocidad adecuada, debe salirse.' },
    { t: '¿Cuál es la velocidad máxima genérica en vías urbanas con dos carriles por sentido?', o: ['30 km/h', '40 km/h', '50 km/h', '60 km/h'], r: 2, s: 'velocidad', d: 1, m: 'velocidad#urbana', e: 'Vías urbanas con 2+ carriles por sentido: 50 km/h.' },
    { t: '¿Cuál es la velocidad máxima para turismos en carretera convencional con arcén de 1,5 m o más?', o: ['80 km/h', '90 km/h', '100 km/h', '110 km/h'], r: 2, s: 'velocidad', d: 2, m: 'velocidad#carretera', e: 'Si el arcén es de 1,5 m o más, se puede circular a 100 km/h.' },
    { t: '¿Cuál es la velocidad máxima al adelantar en autopista?', o: ['120 km/h, no se puede superar el límite', '130 km/h, superando el límite', 'La que permita la vía sin superar 120 km/h', '140 km/h si no hay radares'], r: 0, s: 'velocidad', d: 2, m: 'velocidad#adelantamiento', e: 'En autopista no se puede superar el límite de 120 km/h ni siquiera al adelantar.' },
    { t: 'En una zona de velocidad limitada a 30 km/h, ¿puede circular a 50 km/h un autobús?', o: ['Sí, los autobuses tienen exención', 'No, debe respetar los 30 km/h', 'Sí, si no lleva pasajeros', 'Solo si es de noche'], r: 1, s: 'velocidad', d: 2, m: 'velocidad#urbana-30', e: 'Todos los vehículos deben respetar los límites de velocidad.' },
    { t: '¿Cuál es la distancia de seguridad mínima entre vehículos en carretera convencional?', o: ['La distancia que permita detenerse en caso de frenada brusca del vehículo delantero', '50 metros', '100 metros', 'La distancia recorrida en 1 segundo'], r: 0, s: 'velocidad', d: 1, m: 'velocidad#distancia-seguridad', e: 'Debe mantenerse la distancia que permita detenerse ante una frenada brusca.' },
    { t: '¿A cuántos metros equivale aproximadamente 1 segundo de reacción a 90 km/h?', o: ['15 metros', '20 metros', '25 metros', '30 metros'], r: 2, s: 'velocidad', d: 3, m: 'velocidad#distancias', e: '90 km/h = 25 m/s. En 1 segundo de reacción se recorren 25 metros.' },
    { t: '¿Cuál es la velocidad máxima para un turismo en una autovía de montaña?', o: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'], r: 0, s: 'velocidad', d: 3, m: 'velocidad#autopista', e: 'Autovía de montaña: la DGT puede limitar a 90 o 100 km/h según el trazado.' },

    // === ADELANTAMIENTOS (+12) ===
    { t: '¿Se puede adelantar en un cambio de rasante con visibilidad?', o: ['Sí, si hay suficiente visibilidad', 'No, está prohibido siempre', 'Solo si no hay línea continua', 'Sí, pero con precaución'], r: 0, s: 'adelantamientos', d: 2, m: 'adelantamientos#prohibiciones', e: 'Se puede adelantar en cambio de rasante si hay visibilidad suficiente y no hay línea continua.' },
    { t: '¿Cuándo debe señalizar el final del adelantamiento?', o: ['Al comenzar a reintegrarse al carril', 'Antes de reintegrarse, con el intermitente derecho', 'Al rebasar el vehículo', 'No es necesario señalizar'], r: 1, s: 'adelantamientos', d: 1, m: 'adelantamientos#senalizacion', e: 'La reintegración debe señalizarse con el intermitente derecho.' },
    { t: '¿Está permitido adelantar en un paso a nivel sin barreras?', o: ['Sí, si no viene el tren', 'No, está prohibido', 'Solo si hay visibilidad', 'Sí, en autopista'], r: 1, s: 'adelantamientos', d: 1, m: 'adelantamientos#prohibiciones', e: 'Está prohibido adelantar en pasos a nivel.' },
    { t: '¿Puede un camión adelantar a otro camión en autopista?', o: ['Sí, siempre que sea seguro', 'Sí, pero con limitación de tiempo', 'No, los camiones no pueden adelantar', 'Solo si no hay tráfico'], r: 0, s: 'adelantamientos', d: 1, m: 'adelantamientos#normas', e: 'Los camiones pueden adelantar si es seguro, aunque deben hacerlo eficientemente.' },
    { t: '¿Qué distancia lateral debe dejarse al adelantar a un ciclista en carretera secundaria?', o: ['1 metro', '1,5 metros', '2 metros', '0,5 metros'], r: 1, s: 'adelantamientos', d: 1, m: 'adelantamientos#ciclistas', e: '1,5 metros de separación lateral al adelantar ciclistas.' },
    { t: 'Al adelantar a un grupo de ciclistas, ¿qué debe hacer?', o: ['Adelantar como a un vehículo', 'Reducir la velocidad a 20 km/h menos del límite y dejar 1,5 m', 'Tocar el claxon para que se aparten', 'Esperar detrás de ellos'], r: 1, s: 'adelantamientos', d: 2, m: 'adelantamientos#ciclistas', e: 'Al adelantar ciclistas: reducir velocidad y dejar 1,5 m de separación.' },
    { t: '¿Cuándo está permitido adelantar por la derecha en autopista?', o: ['Nunca', 'Cuando el carril izquierdo esté ocupado y haya densidad de tráfico', 'Siempre que sea seguro', 'Cuando el vehículo de delante va lento'], r: 1, s: 'adelantamientos', d: 1, m: 'adelantamientos#derecha', e: 'En autopista con tráfico denso, si todos los carriles están ocupados, se puede adelantar por la derecha.' },
    { t: '¿Cuánto tiempo puede ocupar el carril izquierdo un camión adelantando?', o: ['El tiempo necesario para adelantar', 'Máximo 2 minutos', 'Máximo 3 minutos', 'No hay límite'], r: 0, s: 'adelantamientos', d: 2, m: 'adelantamientos#normas', e: 'Los camiones deben ocupar el carril izquierdo solo el tiempo necesario para adelantar.' },
    { t: '¿Se puede adelantar en una intersección?', o: ['Sí, si no hay tráfico', 'No, salvo que se adelante a un ciclista o se circule por vía prioritaria', 'Sí, siempre que se señalice', 'Solo si la intersección no tiene semáforo'], r: 1, s: 'adelantamientos', d: 2, m: 'adelantamientos#prohibiciones', e: 'No se puede adelantar en intersecciones, salvo a ciclistas o en vía prioritaria.' },
    { t: '¿Cuando un vehículo adelanta, qué distancia debe mantener respecto al vehículo adelantado al reintegrarse?', o: ['Al menos 50 metros', 'La suficiente para verlo en el retrovisor', '5 metros', 'La distancia de frenado'], r: 1, s: 'adelantamientos', d: 1, m: 'adelantamientos#reintegro', e: 'Debe reintegrarse cuando vea el vehículo adelantado en el espejo retrovisor.' },
    { t: '¿Se puede adelantar a varios vehículos a la vez?', o: ['Sí, si hay suficiente visibilidad y espacio', 'No, solo uno a la vez', 'Solo en autopista', 'Solo si son ciclistas'], r: 0, s: 'adelantamientos', d: 2, m: 'adelantamientos#normas', e: 'Se puede adelantar a varios si hay visibilidad y espacio para reintegrarse.' },
    { t: '¿A qué velocidad máxima se puede adelantar en autopista?', o: ['120 km/h, respetando el límite', '130 km/h', '140 km/h', 'No hay límite al adelantar'], r: 0, s: 'adelantamientos', d: 1, m: 'adelantamientos#normas', e: 'Al adelantar en autopista no se puede superar el límite de velocidad general.' },

    // === PRIORIDAD (+12) ===
    { t: 'En una intersección con semáforo en rojo, ¿qué debe hacer?', o: ['Pasar si no hay peatones', 'Detenerse en la línea de detención', 'Pasar si no vienen coches', 'Reducir la velocidad'], r: 1, s: 'prioridad', d: 1, m: 'prioridad#semaforos', e: 'Semáforo en rojo: detenerse obligatoriamente.' },
    { t: '¿Tienen prioridad los ciclistas en un carril bici?', o: ['Sí, al cruzar una vía deben ser respetados', 'No, deben ceder el paso a los coches', 'Solo si hay semáforo para ellos', 'Depende de la hora'], r: 0, s: 'prioridad', d: 2, m: 'prioridad#ciclistas', e: 'Los ciclistas en carril bici tienen prioridad sobre los vehículos.' },
    { t: '¿Quién tiene prioridad en una vía estrecha de montaña si dos vehículos se encuentran?', o: ['El que sube', 'El que baja', 'El que va más lento', 'El que está más cerca de un ensanche'], r: 0, s: 'prioridad', d: 1, m: 'prioridad#pendientes', e: 'En pendientes estrechas, prioridad al que sube.' },
    { t: 'En un paso para peatones regulado por semáforo, ¿cuándo deben detenerse los vehículos?', o: ['Siempre que haya un peatón esperando', 'Cuando el semáforo esté en rojo para vehículos', 'Solo si el peatón levanta la mano', 'Cuando el peatón esté en el paso'], r: 1, s: 'prioridad', d: 1, m: 'prioridad#semaforos', e: 'Los vehículos deben detenerse con el semáforo en rojo, independientemente de los peatones.' },
    { t: '¿Debe un vehículo ceder el paso a los peatones en una acera?', o: ['Sí, al girar para entrar en una calle', 'No, los peatones deben esperar', 'Solo si hay paso de peatones', 'Depende de la velocidad'], r: 0, s: 'prioridad', d: 2, m: 'prioridad#peatones', e: 'Al girar para entrar en otra calle, debe cederse el paso a los peatones.' },
    { t: 'En una rotonda, ¿qué carril debe usar para salir en la primera salida?', o: ['El carril exterior (derecho)', 'El interior', 'Cualquier carril', 'El central'], r: 0, s: 'prioridad', d: 1, m: 'prioridad#rotondas', e: 'Para salir en la primera salida, debe usarse el carril derecho.' },
    { t: 'Un vehículo que circula por una vía de servicio, ¿tiene prioridad sobre el de la vía principal?', o: ['Sí, siempre', 'No, debe ceder el paso', 'Solo si es más grande', 'Depende de quién llegue primero'], r: 1, s: 'prioridad', d: 2, m: 'prioridad#incorporaciones', e: 'Los vehículos de vías de servicio deben ceder el paso a los de la vía principal.' },
    { t: '¿Quién tiene prioridad al incorporarse desde un carril de aceleración?', o: ['El que se incorpora, si señaliza con el intermitente', 'Los vehículos que ya circulan por la vía principal', 'El más rápido', 'El que está más adelantado'], r: 1, s: 'prioridad', d: 1, m: 'prioridad#incorporaciones', e: 'Los que se incorporan deben ceder el paso a los que ya circulan.' },
    { t: '¿Está permitido bloquear un cruce aunque el semáforo esté en verde si hay atasco?', o: ['Sí, el semáforo en verde da prioridad', 'No, no debe entrar en el cruce si no puede despejarlo', 'Sí, si se toca el claxon', 'Depende de la hora'], r: 1, s: 'prioridad', d: 2, m: 'prioridad#semaforos', e: 'No debe entrarse en un cruce si no se puede despejar, aunque el semáforo esté en verde.' },
    { t: 'En un estrechamiento donde hay un vehículo parado, ¿quién tiene prioridad?', o: ['El vehículo que circula', 'El vehículo parado, si está averiado', 'Depende de quién llegó primero', 'El más grande'], r: 0, s: 'prioridad', d: 2, m: 'prioridad#estrechamientos', e: 'El que circula tiene prioridad sobre el que está parado (salvo que esté realizando una maniobra permitida).' },
    { t: '¿Tienen prioridad los vehículos de transporte escolar al subir o bajar niños?', o: ['Sí, con sus señales luminosas activadas', 'No, deben cumplir las normas generales', 'Solo en vías urbanas', 'Depende de la hora'], r: 0, s: 'prioridad', d: 2, m: 'prioridad#escolar', e: 'Los vehículos de transporte escolar con señales luminosas tienen prioridad.' },
    { t: 'En una intersección con STOP, ¿dónde debe detenerse?', o: ['En la línea de detención, o si no hay, antes de la incorporación', 'En medio del cruce', 'Detrás del vehículo que ya está detenido', 'Donde mejor vea'], r: 0, s: 'prioridad', d: 1, m: 'prioridad#stop', e: 'Debe detenerse en la línea de detención o, si no existe, antes de la incorporación.' },

    // === LUCES (+12) ===
    { t: '¿Qué luces debe usar si circula con lluvia intensa y hay vehículos delante?', o: ['Luces de cruce y antiniebla delantera si es necesario', 'Luces de carretera', 'Solo antiniebla trasera', 'Luces de emergencia'], r: 0, s: 'luces', d: 1, m: 'luces#cruce', e: 'Con lluvia intensa: luces de cruce y antiniebla delantera si es preciso. No usar largas.' },
    { t: '¿Cuándo debe usar las luces antiniebla traseras?', o: ['Con niebla espesa, lluvia torrencial o nevada intensa', 'Siempre que llueve', 'Al anochecer', 'En autopista siempre'], r: 0, s: 'luces', d: 1, m: 'luces#antiniebla-trasera', e: 'Antiniebla trasera: solo con niebla espesa, lluvia torrencial o nevada intensa.' },
    { t: '¿Qué luces son obligatorias en un túnel largo?', o: ['Luces de cruce o carretera', 'Solo las de posición', 'Luces antiniebla', 'Ninguna, si el túnel está iluminado'], r: 0, s: 'luces', d: 1, m: 'luces#tuneles', e: 'En cualquier túnel deben encenderse las luces de cruce o carretera.' },
    { t: '¿Qué indica un semáforo con una luz blanca en forma de peatón?', o: ['Paso de peatones', 'Zona peatonal', 'Semáforo para tranvías', 'Semáforo para ciclistas'], r: 2, s: 'luces', d: 3, m: 'luces#semaforos-especiales', e: 'Las luces blancas con forma de peatón o raya son para tranvías.' },
    { t: '¿Se pueden usar las luces de emergencia al estacionar en doble fila?', o: ['Sí, es obligatorio', 'No, las luces de emergencia no autorizan el estacionamiento ilegal', 'Solo si es por menos de 2 minutos', 'Solo de noche'], r: 1, s: 'luces', d: 2, m: 'luces#emergencias', e: 'Las luces de emergencia no autorizan el estacionamiento irregular.' },
    { t: '¿Cuándo debe usar el alumbrado de corto alcance (cruce) durante el día?', o: ['En túneles, pasos inferiores y condiciones adversas', 'Solo al atardecer', 'En autovía siempre', 'Cuando llueve ligeramente'], r: 0, s: 'luces', d: 1, m: 'luces#cruce', e: 'Las luces de cruce en día son obligatorias en túneles, pasos inferiores y condiciones adversas.' },
    { t: '¿Cuál es la luz que más deslumbra?', o: ['Luces de carretera (largas)', 'Luces antiniebla traseras', 'Luces de cruce', 'Luces LED'], r: 0, s: 'luces', d: 1, m: 'luces#largas', e: 'Las largas tienen máximo alcance y pueden deslumbrar a otros conductores.' },
    { t: '¿Se pueden usar las luces antiniebla delanteras sin niebla?', o: ['Sí, mejoran la visibilidad', 'No, solo cuando haya niebla, lluvia intensa o nieve', 'Sí, en autopista siempre', 'Solo en carretera convencional'], r: 1, s: 'luces', d: 1, m: 'luces#antiniebla', e: 'Antiniebla delantera solo con niebla, lluvia intensa, nevada o nubes de humo.' },
    { t: '¿Qué alumbrado debe encenderse al rebasar a otro vehículo en vía estrecha de noche?', o: ['Luces de carretera', 'Luces de cruce para no deslumbrar', 'Luces antiniebla', 'Intermitentes'], r: 1, s: 'luces', d: 1, m: 'luces#cambio', e: 'Al cruzarse con otro vehículo de noche, usar luces de cruce.' },
    { t: '¿Cuántas luces antiniebla traseras debe tener un turismo?', o: ['Una o dos', 'Dos obligatoriamente', 'Cuatro', 'Ninguna, es opcional'], r: 0, s: 'luces', d: 3, m: 'luces#antiniebla-trasera', e: 'Los turismos deben tener al menos una luz antiniebla trasera (y como máximo dos).' },
    { t: '¿Qué luces son obligatorias al circular durante el día con un ciclomotor?', o: ['Ninguna', 'Luces de cruce (obligatorias 24h)', 'Luces de posición', 'Luces antiniebla'], r: 1, s: 'luces', d: 2, m: 'luces#motos', e: 'Ciclomotores y motocicletas: luces de cruce 24h.' },
    { t: '¿Qué significa una luz roja en la parte trasera de un vehículo que se mueve?', o: ['Que está frenando', 'Que tiene las luces antiniebla encendidas', 'Que está dando marcha atrás', 'Que son los intermitentes'], r: 0, s: 'luces', d: 1, m: 'luces#frenos', e: 'Las luces de freno son rojas y se encienden al pisar el freno.' },

    // === ALCOHOL Y CONDUCCIÓN (+10) ===
    { t: '¿Cuánto tiempo tarda en eliminarse una copa de vino?', o: ['30 minutos', 'Aproximadamente 1 hora', '2 horas', 'Inmediatamente'], r: 1, s: 'alcohol', d: 2, m: 'alcohol#eliminacion', e: 'El cuerpo elimina aproximadamente una copa de vino por hora.' },
    { t: '¿Qué hacer si ha bebido y tiene que conducir?', o: ['Esperar unas horas o no conducir', 'Beber café para contrarrestar', 'Ducharse con agua fría', 'Conducir despacio'], r: 0, s: 'alcohol', d: 1, m: 'alcohol#recomendaciones', e: 'La única solución segura es esperar o no conducir.' },
    { t: '¿Qué tasa de alcohol en aire espirado se considera delito penal?', o: ['0,25 mg/l', '0,50 mg/l o superior', '0,60 mg/l', '0,15 mg/l'], r: 1, s: 'alcohol', d: 2, m: 'alcohol#sanciones', e: 'A partir de 0,50 mg/l (0,60 mg/l en algunas fuentes) en aire espirado se considera delito.' },
    { t: '¿Qué efectos tienen las drogas en la conducción?', o: ['Mejoran la concentración', 'Alteran la percepción, el tiempo de reacción y la coordinación', 'Solo afectan si se mezclan con alcohol', 'No afectan a corto plazo'], r: 1, s: 'alcohol', d: 1, m: 'alcohol#drogas', e: 'Todas las drogas alteran la percepción, los reflejos y la capacidad de conducir.' },
    { t: '¿Puede un conductor negarse a realizar la prueba de alcoholemia?', o: ['Sí, es un derecho', 'No, negarse es delito penal', 'Sí, pero con multa', 'Solo si se tiene abogado'], r: 1, s: 'alcohol', d: 1, m: 'alcohol#sanciones', e: 'Negarse al control de alcoholemia es delito penal (prisión de 6 meses a 1 año).' },
    { t: '¿Cuánto alcohol tiene aproximadamente una cerveza (33 cl)?', o: ['5-10 g', '10-15 g', '15-20 g', '20-25 g'], r: 1, s: 'alcohol', d: 3, m: 'alcohol#contenido', e: 'Una cerveza de 33 cl con 5º contiene unos 13 g de alcohol puro.' },
    { t: '¿Conducir con resaca es peligroso?', o: ['Sí, los efectos del alcohol persisten', 'No, una vez dormido se elimina', 'Solo si se ha bebido mucho', 'No, si se desayuna bien'], r: 0, s: 'alcohol', d: 1, m: 'alcohol#resaca', e: 'La resaca sigue afectando a la capacidad de conducir.' },
    { t: '¿Pueden las bebidas "sin alcohol" dar positivo?', o: ['No, son seguras', 'Sí, algunas contienen hasta 0,9% de alcohol', 'Solo si se mezclan con otras', 'Depende del metabolismo'], r: 1, s: 'alcohol', d: 3, m: 'alcohol#sin-alcohol', e: 'Las bebidas "sin alcohol" pueden contener hasta 0,9% de alcohol.' },
    { t: '¿Qué ocurre si se supera la tasa de alcohol en más del doble siendo conductor novel?', o: ['Multa de 500€', 'Delito penal con penas de prisión y retirada del carnet', 'Solo pérdida de puntos', 'Multa de 1000€'], r: 1, s: 'alcohol', d: 2, m: 'alcohol#sanciones', e: 'Superar el doble de la tasa es delito penal.' },
    { t: '¿Cuántas horas se necesitan para eliminar completamente 3 copas de vino?', o: ['3 horas', '6 horas aproximadamente', '12 horas', '24 horas'], r: 1, s: 'alcohol', d: 2, m: 'alcohol#eliminacion', e: 'Si cada copa tarda ~1 hora en eliminarse, 3 copas necesitan ~3 horas mínimo.' },

    // === SEGURIDAD VIAL (+14) ===
    { t: '¿Cuánto reduce el cinturón el riesgo de muerte en caso de accidente?', o: ['Un 25%', 'Un 50% en asientos delanteros', 'Un 75%', 'No reduce significativamente'], r: 1, s: 'seguridad', d: 1, m: 'seguridad#cinturon', e: 'El cinturón reduce un 50% el riesgo de muerte en los asientos delanteros.' },
    { t: '¿Qué distancia de seguridad debe mantener con el vehículo delantero en condiciones normales?', o: ['La distancia recorrida en 2 segundos', '50 metros', '30 metros', 'La distancia recorrida en 1 segundo'], r: 0, s: 'seguridad', d: 1, m: 'seguridad#distancias', e: 'Regla de los 2 segundos: esa es la distancia mínima.' },
    { t: '¿Qué es el "punto ciego" de un vehículo?', o: ['El punto donde el airbag no protege', 'El ángulo que no se ve por los espejos retrovisores', 'El espacio detrás del vehículo', 'La zona delantera del capó'], r: 1, s: 'seguridad', d: 1, m: 'seguridad#puntos-ciegos', e: 'El punto ciego es la zona que no se ve por los espejos.' },
    { t: '¿Cuánto debe durar un viaje antes de hacer una pausa?', o: ['Cada 1 hora', 'Cada 2 horas o 200 km', 'No es necesario parar', 'Cada 4 horas'], r: 1, s: 'seguridad', d: 1, m: 'seguridad#fatiga', e: 'Se recomienda parar cada 2 horas o 200 km para descansar.' },
    { t: '¿Qué es la fatiga en la conducción?', o: ['Cansancio que reduce la capacidad de reacción y atención', 'Un tipo de sueño', 'Solo ocurre de noche', 'Es una enfermedad'], r: 0, s: 'seguridad', d: 1, m: 'seguridad#fatiga', e: 'La fatiga reduce reflejos y atención. Síntomas: bostezos, pesadez de ojos.' },
    { t: '¿Cuál es la profundidad mínima del dibujo del neumático recomendada por seguridad?', o: ['1,6 mm (legal)', 'Se recomienda cambiar a partir de 3 mm', '2 mm', 'No hay recomendación'], r: 1, s: 'seguridad', d: 2, m: 'seguridad#neumaticos', e: 'Aunque lo legal es 1,6mm, se recomienda cambiar a partir de 3 mm por seguridad.' },
    { t: '¿Qué ocurre si se explota un airbag con el asiento muy cerca del volante?', o: ['Nada, está diseñado para eso', 'Puede causar lesiones graves porque la distancia de seguridad es de 25 cm', 'Funciona igual', 'Se despliega más suave'], r: 1, s: 'seguridad', d: 2, m: 'seguridad#airbag', e: 'Debe mantenerse 25 cm de distancia entre el volante y el conductor.' },
    { t: '¿Qué debe hacer si un neumático explosiona en autopista?', o: ['Frenar a fondo', 'Sujetar el volante, no frenar bruscamente y reducir velocidad gradualmente', 'Acelerar para estabilizar', 'Apagar el motor'], r: 1, s: 'seguridad', d: 1, m: 'seguridad#emergencias', e: 'Ante reventón: sujetar volante, no frenar brusco, reducir velocidad suavemente.' },
    { t: '¿Cada cuánto debe revisarse el nivel de aceite del motor?', o: ['Cada semana', 'Cada mes', 'Cada 5000 km', 'Cada cambio de aceite'], r: 0, s: 'seguridad', d: 2, m: 'seguridad#mantenimiento', e: 'Se recomienda revisar el aceite semanalmente o cada 1000 km.' },
    { t: '¿Qué indica la luz roja del testigo de presión de aceite?', o: ['Que el aceite está bajo', 'Que la presión de aceite es insuficiente, detenerse inmediatamente', 'Que toca cambiar el aceite', 'Que el motor está caliente'], r: 1, s: 'seguridad', d: 2, m: 'seguridad#testigos', e: 'Luz roja de presión de aceite: detenerse de inmediato para evitar daños al motor.' },
    { t: '¿Qué es el "efecto suelo"?', o: ['La adherencia del vehículo al asfalto a alta velocidad', 'La distancia al suelo del vehículo', 'Un tipo de suspensión', 'La resistencia al viento'], r: 0, s: 'seguridad', d: 3, m: 'seguridad#' },
    { t: '¿Cuándo debe usar el freno de mano?', o: ['Al estacionar para inmovilizar el vehículo', 'Para frenar en emergencias', 'En pendientes al arrancar', 'En todas las paradas'], r: 0, s: 'seguridad', d: 1, m: 'seguridad#freno-mano', e: 'El freno de mano se usa para inmovilizar el vehículo al estacionar.' },
    { t: '¿Cuánto aumenta la distancia de frenado en una vía mojada respecto a una seca?', o: ['Se duplica', 'Puede duplicarse o más', 'Aumenta un 50%', 'No varía significativamente'], r: 1, s: 'seguridad', d: 1, m: 'seguridad#frenado', e: 'En mojado la distancia de frenado puede duplicarse o incluso triplicarse.' },
    { t: '¿Qué es el control de estabilidad (ESP)?', o: ['Un sistema que evita que el conductor pierda el control del vehículo', 'Un sistema de frenada de emergencia', 'Un regulador de velocidad', 'Un sistema de airbags'], r: 0, s: 'seguridad', d: 2, m: 'seguridad#esp', e: 'El ESP ayuda a mantener la trayectoria y evitar derrapes.' },
    { t: '¿Cuál es la presión correcta de los neumáticos?', o: ['La indicada por el fabricante del vehículo', 'La máxima que soporte el neumático', '2,5 bares siempre', 'Depende de la velocidad'], r: 0, s: 'seguridad', d: 1, m: 'seguridad#neumaticos', e: 'La presión correcta es la recomendada por el fabricante (en el manual, pilar puerta o tapa gasolina).' },
    { t: '¿Se pueden llevar niños en brazos en el asiento delantero?', o: ['Sí, si van con cinturón', 'No, está prohibido', 'Solo si no hay airbag', 'Solo en viajes cortos'], r: 1, s: 'seguridad', d: 1, m: 'seguridad#infantil', e: 'Está prohibido llevar niños en brazos. Deben ir en su SRI homologado.' },
    { t: '¿Qué es el ABS?', o: ['Un sistema antibloqueo de frenos', 'Un sistema de airbags', 'Un control de tracción', 'Un asistente de arranque en pendiente'], r: 0, s: 'seguridad', d: 1, m: 'seguridad#abs', e: 'ABS evita que las ruedas se bloqueen al frenar, manteniendo el control direccional.' },
  ];

  for (const p of extras) {
    const temaId = temaMap[p.s];
    if (temaId) {
      insertPregunta.run(p.t, JSON.stringify(p.o), p.r, temaId, p.d, p.m || null, p.e || null, p.img || null);
    }
  }

  db.prepare("INSERT OR IGNORE INTO seed_meta (marca) VALUES ('preguntas_extra_v1')").run();
}
